//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SDAirDropHandlerGenericLinks.h"

__attribute__((visibility("hidden")))
@interface SDAirDropHandlerNewsLinks : SDAirDropHandlerGenericLinks
{
}

- (id)suitableContentsDescription;	// IMP=0x000000010003f990
- (long long)transferTypes;	// IMP=0x000000010003f958
- (_Bool)canHandleTransfer;	// IMP=0x000000010003f938
- (id)candidateIdentifiers;	// IMP=0x000000010003f884
- (id)initWithTransfer:(id)arg1;	// IMP=0x000000010003f820

@end

