//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SDAirDropHandlerGenericLinks.h"

@class NSString, SDAirDropHandlerWebLinks;

__attribute__((visibility("hidden")))
@interface SDAirDropHandleriWorkLinks : SDAirDropHandlerGenericLinks
{
    NSString *_appName;	// 8 = 0x8
    SDAirDropHandlerWebLinks *_webLinksHandler;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010010196c
- (void)updatePossibleActions;	// IMP=0x00000001001018c0
- (id)suitableContentsDescription;	// IMP=0x0000000100101654
- (id)documentName;	// IMP=0x00000001001015b4
- (id)bundleProxyForiWorkURL:(id)arg1;	// IMP=0x00000001001013e8
- (long long)transferTypes;	// IMP=0x00000001001013b0
- (_Bool)canHandleTransfer;	// IMP=0x00000001001011a4
- (id)initWithTransfer:(id)arg1;	// IMP=0x0000000100101170

@end

