//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SDAirDropHandlerGenericLinks.h"

__attribute__((visibility("hidden")))
@interface SDAirDropHandlerAppStoreLinks : SDAirDropHandlerGenericLinks
{
}

- (id)suitableContentsDescription;	// IMP=0x0000000100104edc
- (long long)transferTypes;	// IMP=0x0000000100104ea4
- (id)singleItemActionTitle;	// IMP=0x0000000100104e98
- (_Bool)canHandleTransfer;	// IMP=0x0000000100104e78
- (id)candidateIdentifiers;	// IMP=0x0000000100104da0
- (id)initWithTransfer:(id)arg1;	// IMP=0x0000000100104d64

@end

