//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "UNUserNotificationCenterDelegate-Protocol.h"

@class NSMutableDictionary, NSSet, NSString, UNUserNotificationCenter;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface SDNotificationManager : NSObject <UNUserNotificationCenterDelegate>
{
    _Bool _activated;	// 8 = 0x8
    NSMutableDictionary *_autoFillRequests;	// 16 = 0x10
    UNUserNotificationCenter *_homePodNotifCenter;	// 24 = 0x18
    _Bool _homePodNotifGranted;	// 32 = 0x20
    NSMutableDictionary *_homePodRequests;	// 40 = 0x28
    _Bool _invalidated;	// 48 = 0x30
    NSMutableDictionary *_tvKeyboardRequests;	// 56 = 0x38
    UNUserNotificationCenter *_tvNotifCenter;	// 64 = 0x40
    _Bool _tvNotifGranted;	// 72 = 0x48
    NSMutableDictionary *_watchKeyboardRequests;	// 80 = 0x50
    UNUserNotificationCenter *_watchNotifCenter;	// 88 = 0x58
    _Bool _watchNotifGranted;	// 96 = 0x60
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 104 = 0x68
}

+ (id)sharedManager;	// IMP=0x000000010012b708
- (void).cxx_destruct;	// IMP=0x00000001001335e8
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
- (void)testWatchKeyboardAutoFill;	// IMP=0x00000001001334e4
- (void)testWatchKeyboard;	// IMP=0x0000000100133408
- (void)testKeyboardUpdate;	// IMP=0x0000000100133334
- (void)testKeyboardRemove;	// IMP=0x0000000100133258
- (void)testKeyboardPostAutoFill;	// IMP=0x0000000100133164
- (void)testKeyboardPost;	// IMP=0x0000000100133084
- (void)testHandoffPost;	// IMP=0x0000000100132eb4
- (void)testAutoFillRemove;	// IMP=0x0000000100132dd8
- (void)testAutofillPost;	// IMP=0x0000000100132cfc
- (void)testPostBasic;	// IMP=0x0000000100132bb0
- (void)testPost:(id)arg1;	// IMP=0x00000001001329b4
- (void)userNotificationCenter:(id)arg1 didReceiveNotificationResponse:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001001324bc
- (void)_homePodHandleResponse:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100131f98
- (void)_homePodHandoffUpdateIfNeeded:(id)arg1 info:(id)arg2;	// IMP=0x0000000100131b14
- (void)homePodHandoffUpdateIfNeeded:(id)arg1 info:(id)arg2;	// IMP=0x0000000100131a38
- (void)_homePodHandoffRemoveAll;	// IMP=0x0000000100131994
- (void)homePodHandoffRemoveAll;	// IMP=0x000000010013192c
- (void)_homePodHandoffRemove:(id)arg1 reason:(long long)arg2;	// IMP=0x00000001001316ec
- (void)homePodHandoffRemove:(id)arg1 reason:(long long)arg2;	// IMP=0x0000000100131640
- (void)_homePodHandoffPostIfNeeded:(id)arg1 info:(id)arg2;	// IMP=0x0000000100131484
- (void)homePodHandoffPostIfNeeded:(id)arg1 info:(id)arg2;	// IMP=0x00000001001313a8
- (id)homePodHandoffContentForDevice:(id)arg1 info:(id)arg2;	// IMP=0x0000000100130e88
- (void)_watchHandleResponse:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100130dd8
- (void)_watchKeyboardUpdate:(id)arg1 rtiData:(id)arg2;	// IMP=0x0000000100130740
- (void)watchKeyboardUpdate:(id)arg1 rtiData:(id)arg2;	// IMP=0x0000000100130664
- (void)_watchKeyboardUpdate:(id)arg1 info:(id)arg2;	// IMP=0x00000001001301f0
- (void)watchKeyboardUpdate:(id)arg1 info:(id)arg2;	// IMP=0x0000000100130114
- (void)_watchKeyboardRemoveAll;	// IMP=0x0000000100130084
- (void)watchKeyboardRemoveAll;	// IMP=0x000000010013001c
- (void)_watchKeyboardRemove:(id)arg1;	// IMP=0x000000010012fe88
- (void)watchKeyboardRemove:(id)arg1;	// IMP=0x000000010012fdf0
- (void)_watchKeyboardPostIfNeeded:(id)arg1;	// IMP=0x000000010012fc5c
- (void)watchKeyboardPostIfNeeded:(id)arg1;	// IMP=0x000000010012fbc4
- (id)watchKeyboardContentForDevice:(id)arg1;	// IMP=0x000000010012f8e0
- (void)_tvAutoFillRemoveAll;	// IMP=0x000000010012f83c
- (void)tvAutoFillRemoveAll;	// IMP=0x000000010012f7d4
- (void)_tvAutoFillRemove:(id)arg1;	// IMP=0x000000010012f640
- (void)tvAutoFillRemove:(id)arg1;	// IMP=0x000000010012f5a8
- (void)_tvAutoFillPostIfNeeded:(id)arg1;	// IMP=0x000000010012f234
- (void)tvAutoFillPostIfNeeded:(id)arg1;	// IMP=0x000000010012f19c
@property(readonly, copy, nonatomic) NSSet *activeTVAutoFillPrompts;
- (void)_tvKeyboardUpdate:(id)arg1 rtiData:(id)arg2;	// IMP=0x000000010012ea8c
- (void)tvKeyboardUpdate:(id)arg1 rtiData:(id)arg2;	// IMP=0x000000010012e9b0
- (void)_tvKeyboardUpdate:(id)arg1 info:(id)arg2;	// IMP=0x000000010012e53c
- (void)tvKeyboardUpdate:(id)arg1 info:(id)arg2;	// IMP=0x000000010012e460
- (void)_tvKeyboardRemoveAll;	// IMP=0x000000010012e3d0
- (void)tvKeyboardRemoveAll;	// IMP=0x000000010012e368
- (void)_tvKeyboardRemove:(id)arg1;	// IMP=0x000000010012e1d4
- (void)tvKeyboardRemove:(id)arg1;	// IMP=0x000000010012e13c
- (void)_tvKeyboardPostIfNeeded:(id)arg1 backgroundAction:(_Bool)arg2;	// IMP=0x000000010012df78
- (void)tvKeyboardPostIfNeeded:(id)arg1 backgroundAction:(_Bool)arg2;	// IMP=0x000000010012decc
- (id)tvKeyboardContentForDevice:(id)arg1 backgroundAction:(_Bool)arg2;	// IMP=0x000000010012dbc8
- (void)_tvHandleResponse:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010012d560
- (id)attachmentFromURL:(id)arg1;	// IMP=0x000000010012d348
- (void)_addRequestWithID:(id)arg1 content:(id)arg2 type:(unsigned int)arg3;	// IMP=0x000000010012cb24
- (void)_homePodEnsureStarted:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010012c720
- (void)_watchEnsureStarted:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010012c31c
- (void)_tvEnsureStarted:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x000000010012bf0c
- (void)_update;	// IMP=0x000000010012be90
- (void)prefsChanged;	// IMP=0x000000010012be84
- (void)_invalidate;	// IMP=0x000000010012be24
- (void)invalidate;	// IMP=0x000000010012bdbc
- (void)_activate;	// IMP=0x000000010012bd20
- (void)activate;	// IMP=0x000000010012bcb8
@property(readonly, copy) NSString *description;
- (id)init;	// IMP=0x000000010012b774

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

