//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary, RPPeopleDiscovery, SDXPCHelperConnection;

__attribute__((visibility("hidden")))
@interface SDRapportBrowser : NSObject
{
    long long _startCount;	// 8 = 0x8
    NSMutableDictionary *_cachedNodes;	// 16 = 0x10
    RPPeopleDiscovery *_peopleDiscovery;	// 24 = 0x18
    SDXPCHelperConnection *_helperConnection;	// 32 = 0x20
}

+ (id)deviceTypeFromModelIdentifier:(id)arg1;	// IMP=0x00000001000aed68
+ (id)deviceImageNameFromModelIdentifier:(id)arg1;	// IMP=0x00000001000ae924
+ (_Bool)deviceIsEligibleForAirDrop:(id)arg1;	// IMP=0x00000001000ae834
+ (_Bool)personHasAirDropEligibleDevice:(id)arg1;	// IMP=0x00000001000ae6f0
+ (id)identifiersForPerson:(id)arg1;	// IMP=0x00000001000ae5f0
+ (unsigned long long)defaultSFNodeFlags;	// IMP=0x00000001000addc8
+ (void)updateRangingMeasurementForDevice:(id)arg1 inNode:(struct __SFNode *)arg2;	// IMP=0x00000001000add28
+ (void)updateRangingMeasurementForPerson:(id)arg1 inNode:(struct __SFNode *)arg2;	// IMP=0x00000001000adae4
+ (id)sharedRapportBrowser;	// IMP=0x00000001000ac4a8
- (void).cxx_destruct;	// IMP=0x00000001000aeeb8
@property(nonatomic) __weak SDXPCHelperConnection *helperConnection; // @synthesize helperConnection=_helperConnection;
- (struct __SFNode *)createSFNodeFromMyRPDevice:(id)arg1;	// IMP=0x00000001000ae4c8
- (struct __SFNode *)createSFNodeFromRPPerson:(id)arg1;	// IMP=0x00000001000ae304
- (struct __SFNode *)createSFNodeFromCNContact:(id)arg1 identifier:(id)arg2 device:(id)arg3;	// IMP=0x00000001000addd0
- (void)resumeHandoffAdvertisingIfAppropriate;	// IMP=0x00000001000ada50
- (void)stopHandoffAdvertisingIfAppropriate;	// IMP=0x00000001000ad9bc
- (_Bool)shouldStopHandoffAdvertising;	// IMP=0x00000001000ad990
- (id)assertionIdentifier;	// IMP=0x00000001000ad958
- (void)removeNodesForPerson:(id)arg1;	// IMP=0x00000001000ad8e4
- (void)addOrUpdateNodesForPerson:(id)arg1 withChanges:(unsigned int)arg2;	// IMP=0x00000001000ad358
@property(readonly, copy) NSArray *nodes;
- (void)removeObservers;	// IMP=0x00000001000ad2f8
- (void)addObservers;	// IMP=0x00000001000ad290
- (void)contactsChanged:(id)arg1;	// IMP=0x00000001000ad108
- (void)_stop;	// IMP=0x00000001000ad05c
- (void)_start;	// IMP=0x00000001000ac6e8
- (void)stop;	// IMP=0x00000001000ac614
- (void)start;	// IMP=0x00000001000ac548
- (id)init;	// IMP=0x00000001000ac514

@end

