//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SDBonjourBrowserDelegate-Protocol.h"
#import "SDWindowsBrowserDelegate-Protocol.h"

@class NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface SDServerBrowser : NSObject <SDBonjourBrowserDelegate, SDWindowsBrowserDelegate>
{
    long long _mode;	// 8 = 0x8
    NSMutableDictionary *_odiskBrowsers;	// 16 = 0x10
    NSMutableDictionary *_bonjourBrowsers;	// 24 = 0x18
    NSMutableDictionary *_windowsBrowsers;	// 32 = 0x20
    NSMutableDictionary *_airDropBrowsers;	// 40 = 0x28
}

+ (id)sharedBrowser;	// IMP=0x00000001000d4194
- (void).cxx_destruct;	// IMP=0x00000001000d6600
@property(readonly, copy) NSString *description;
- (id)stringForBrowserMode:(long long)arg1;	// IMP=0x00000001000d5cb4
- (void)stopBrowsingWorkgroup:(id)arg1;	// IMP=0x00000001000d5b6c
- (id)windowsNodesForWorkgroup:(id)arg1;	// IMP=0x00000001000d5ac8
- (void)startBrowsingWorkgroup:(id)arg1;	// IMP=0x00000001000d593c
- (void)stopAirDropBrowsing:(id)arg1;	// IMP=0x00000001000d5760
- (_Bool)isAirDropEnabled;	// IMP=0x00000001000d5738
- (id)airDropNodesForDomain:(id)arg1;	// IMP=0x00000001000d5694
- (void)incrementTransfersCompleted;	// IMP=0x00000001000d55ac
- (void)incrementTransfersInitiated;	// IMP=0x00000001000d54e8
- (void)setIconData:(id)arg1 iconHash:(id)arg2 forPerson:(struct __SFNode *)arg3;	// IMP=0x00000001000d5418
- (void)startAirDropBrowsing:(id)arg1 connection:(id)arg2 sessionID:(id)arg3;	// IMP=0x00000001000d515c
- (void)startAirDropBrowsing:(id)arg1 bundleID:(id)arg2 sessionID:(id)arg3 helperConnection:(id)arg4;	// IMP=0x00000001000d4e70
- (void)stopODiskBrowsing:(id)arg1;	// IMP=0x00000001000d4cfc
- (id)odiskNodesForDomain:(id)arg1;	// IMP=0x00000001000d4c58
- (void)startODiskBrowsing:(id)arg1;	// IMP=0x00000001000d4a50
- (void)stopBrowsingDomain:(id)arg1;	// IMP=0x00000001000d48dc
- (id)bonjourNodesForDomain:(id)arg1;	// IMP=0x00000001000d4838
- (void)setBonjourBrowserMode:(long long)arg1;	// IMP=0x00000001000d4790
- (void)startBrowsingDomain:(id)arg1;	// IMP=0x00000001000d454c
- (void)windowsNodesDidChange:(id)arg1;	// IMP=0x00000001000d44f4
- (void)bonjourNodesDidChange:(id)arg1;	// IMP=0x00000001000d43bc
- (void)postNotification:(id)arg1 forNeighborhood:(id)arg2;	// IMP=0x00000001000d42b0
- (id)init;	// IMP=0x00000001000d4200

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

