//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface SDUnlockDisable : PBCodable <NSCopying>
{
    NSString *_pairingID;	// 8 = 0x8
    unsigned int _version;	// 16 = 0x10
    CDStruct_f20694ce _has;	// 20 = 0x14
}

- (void).cxx_destruct;	// IMP=0x00000001000ba590
@property(retain, nonatomic) NSString *pairingID; // @synthesize pairingID=_pairingID;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void)mergeFrom:(id)arg1;	// IMP=0x00000001000ba4e4
- (unsigned long long)hash;	// IMP=0x00000001000ba480
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001000ba3a8
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000ba300
- (void)copyTo:(id)arg1;	// IMP=0x00000001000ba288
- (void)writeTo:(id)arg1;	// IMP=0x00000001000ba218
- (_Bool)readFrom:(id)arg1;	// IMP=0x00000001000ba210
- (id)dictionaryRepresentation;	// IMP=0x00000001000b9eec
- (id)description;	// IMP=0x00000001000b9e38
@property(readonly, nonatomic) _Bool hasPairingID;
@property(nonatomic) _Bool hasVersion;

@end

