//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TVAirPlayAPRKSession-Protocol.h"

@class APRKStreamRenderer, NSString, UIView, UIViewController;
@protocol OS_dispatch_source, TVAirPlayAPRKSessionDelegate;

@interface TVAirPlayAPRKVideoSession : NSObject <TVAirPlayAPRKSession>
{
    id <TVAirPlayAPRKSessionDelegate> _delegate;	// 8 = 0x8
    APRKStreamRenderer *_streamRenderer;	// 16 = 0x10
    UIView *_videoView;	// 24 = 0x18
    UIViewController *_videoViewController;	// 32 = 0x20
    NSObject<OS_dispatch_source> *_userActivityTimer;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x000000010001b7f4
@property(retain, nonatomic) NSObject<OS_dispatch_source> *userActivityTimer; // @synthesize userActivityTimer=_userActivityTimer;
@property(retain, nonatomic) UIViewController *videoViewController; // @synthesize videoViewController=_videoViewController;
@property(retain, nonatomic) UIView *videoView; // @synthesize videoView=_videoView;
@property(retain, nonatomic) APRKStreamRenderer *streamRenderer; // @synthesize streamRenderer=_streamRenderer;
@property(nonatomic) __weak id <TVAirPlayAPRKSessionDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_cancelUserActivityTimer;	// IMP=0x000000010001b738
- (void)_startUserActivityTimer;	// IMP=0x000000010001b638
- (void)userStop;	// IMP=0x000000010001b4fc
- (void)wasDeregistered;	// IMP=0x000000010001b4f0
- (void)wasRegistered;	// IMP=0x000000010001b47c
@property(readonly, nonatomic) long long sessionType;
@property(readonly, copy) NSString *description;
- (void)dealloc;	// IMP=0x000000010001b1e4
- (id)initWithStreamRenderer:(id)arg1;	// IMP=0x000000010001b16c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

