//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "GCDaemonXPCInterface-Protocol.h"
#import "GCRemoteDaemonProxy-Protocol.h"
#import "NSXPCListenerDelegate-Protocol.h"

@class NSMutableArray, NSString, NSXPCConnection;

@interface GCDGameControllerDaemonDelegate : NSObject <NSXPCListenerDelegate, GCRemoteDaemonProxy, GCDaemonXPCInterface>
{
    NSMutableArray *_appConnections;	// 8 = 0x8
    NSMutableArray *_foregroundAppConnections;	// 16 = 0x10
    NSXPCConnection *_mediaremoted;	// 24 = 0x18
    NSMutableArray *_hidConnections;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0000000100007540
- (void)appDidEnterBackgroundWithPID:(int)arg1;	// IMP=0x0000000100007308
- (void)appWillEnterForegroundWithPID:(int)arg1;	// IMP=0x00000001000070cc
- (void)appDidEnterBackground;	// IMP=0x0000000100007054
- (void)appWillEnterForeground;	// IMP=0x0000000100006fdc
- (void)removeController:(id)arg1 forward:(_Bool)arg2;	// IMP=0x0000000100006dac
- (void)controllerDidDisconnect:(id)arg1;	// IMP=0x0000000100006d58
- (void)addController:(id)arg1 forward:(_Bool)arg2;	// IMP=0x0000000100005230
- (void)controllerDidConnect:(id)arg1;	// IMP=0x00000001000051dc
- (void)processMicroControllerWithUDID:(unsigned long long)arg1 setDigitizerX:(float)arg2 withY:(float)arg3 withTimeStamp:(unsigned long long)arg4 touchDown:(_Bool)arg5;	// IMP=0x0000000100005024
- (void)microControllerWithUDID:(unsigned long long)arg1 setDigitizerX:(float)arg2 digitizerY:(float)arg3 withTimeStamp:(unsigned long long)arg4 touchDown:(_Bool)arg5;	// IMP=0x0000000100004ed8
- (void)microControllerWithDigitizerX:(float)arg1 withY:(float)arg2 withTimeStamp:(unsigned long long)arg3 touchDown:(_Bool)arg4;	// IMP=0x0000000100004e60
- (void)controllerWithUDID:(unsigned long long)arg1 setArrayValue:(CDStruct_212a8bf9)arg2 forElement:(int)arg3 forward:(_Bool)arg4;	// IMP=0x0000000100004c88
- (void)controllerWithUDID:(unsigned long long)arg1 setValue:(float)arg2 forElement:(int)arg3 forward:(_Bool)arg4;	// IMP=0x0000000100004a28
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x0000000100004814
- (_Bool)acceptNewConnectionFromHIDPlugin:(id)arg1;	// IMP=0x00000001000040dc
- (_Bool)acceptNewConnectionFromMediaRemote:(id)arg1;	// IMP=0x0000000100003dfc
- (_Bool)acceptNewConnection:(id)arg1 fromGCEnabledApp:(id)arg2;	// IMP=0x0000000100003888
- (_Bool)shouldKeepRunning;	// IMP=0x0000000100003880
- (void)ping;	// IMP=0x0000000100003808
- (void)dealloc;	// IMP=0x0000000100003770
- (id)init;	// IMP=0x00000001000036dc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

