//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "APSConnectionDelegate-Protocol.h"

@class APSConnection, NSString;

@interface MSDPushNotificationHandler : NSObject <APSConnectionDelegate>
{
    NSString *_apsToken;	// 8 = 0x8
    APSConnection *_apsConnection;	// 16 = 0x10
}

+ (id)sharedInstance;	// IMP=0x00000001000773a8
- (void).cxx_destruct;	// IMP=0x000000010007788c
@property(retain) APSConnection *apsConnection; // @synthesize apsConnection=_apsConnection;
@property(retain) NSString *apsToken; // @synthesize apsToken=_apsToken;
- (void)connection:(id)arg1 didReceiveToken:(id)arg2 forTopic:(id)arg3 identifier:(id)arg4;	// IMP=0x00000001000777d0
- (void)connection:(id)arg1 didReceiveIncomingMessage:(id)arg2;	// IMP=0x0000000100077678
- (void)connection:(id)arg1 didReceivePublicToken:(id)arg2;	// IMP=0x0000000100077674
- (void)enablePushNotifications;	// IMP=0x00000001000774a0
- (id)init;	// IMP=0x0000000100077414

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

