//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSURL.h>

@interface NSURL (filePath)
+ (id)fileURLWithString:(id)arg1;	// IMP=0x00000001000143ac
- (id)directoryHash;	// IMP=0x000000010002fc60
- (id)fileHash;	// IMP=0x000000010002f890
@end

