//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NESMFilterSessionState.h"

@interface NESMFilterSessionStateUpdating : NESMFilterSessionState
{
}

- (void)handleStop;	// IMP=0x000000010005c2f0
- (void)enterWithSession:(id)arg1;	// IMP=0x000000010005c280
- (id)init;	// IMP=0x000000010005c244

@end

