//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NESMVPNSessionState.h"

@interface NESMVPNSessionStateReasserting : NESMVPNSessionState
{
    _Bool _setConfigurationInProgress;	// 40 = 0x28
}

@property _Bool setConfigurationInProgress; // @synthesize setConfigurationInProgress=_setConfigurationInProgress;
- (void)handleSetConfigurationResult:(_Bool)arg1;	// IMP=0x0000000100068de4
- (_Bool)handleSetConfiguration;	// IMP=0x0000000100068d84
- (void)handleUserLogout;	// IMP=0x0000000100068d50
- (void)handleUserSwitch;	// IMP=0x0000000100068d1c
- (void)handleWakeup;	// IMP=0x0000000100068c8c
- (_Bool)handleSleep;	// IMP=0x0000000100068a7c
- (void)handlePluginStatusDidChangeToConnected:(id)arg1;	// IMP=0x00000001000689f4
- (void)handleTimeout;	// IMP=0x0000000100068944
- (void)handleInterfaceAvailable:(id)arg1 changed:(_Bool)arg2;	// IMP=0x0000000100068764
- (void)enterWithSession:(id)arg1;	// IMP=0x00000001000686cc
- (id)init;	// IMP=0x0000000100068690

@end

