//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NRDUpdateBrainDelegateInterface-Protocol.h"
#import "SUCoreFSMDelegate-Protocol.h"
#import "SUCoreMobileAssetDelegate-Protocol.h"

@class MAAsset, NSBackgroundActivityScheduler, NSDictionary, NSNumber, NSString, SUCoreFSM, SUCoreMobileAsset, SUCorePolicyUpdateBrain, SUCoreScan;
@protocol NRDUpdateDCoreDelegate, OS_dispatch_queue, OS_dispatch_semaphore;

@interface NRDUpdateDCore : NSObject <SUCoreMobileAssetDelegate, NRDUpdateBrainDelegateInterface, SUCoreFSMDelegate>
{
    NSObject<OS_dispatch_semaphore> *_fsmSemaphore;	// 8 = 0x8
    _Bool _forceBrainUpdate;	// 16 = 0x10
    int _keyBagStateChangedNotifyToken;	// 20 = 0x14
    NSDictionary *_stateTable;	// 24 = 0x18
    SUCoreFSM *_updatedFSM;	// 32 = 0x20
    MAAsset *_updateBrainAsset;	// 40 = 0x28
    MAAsset *_localBrainAsset;	// 48 = 0x30
    NSString *_uuid;	// 56 = 0x38
    SUCoreScan *_scanner;	// 64 = 0x40
    SUCorePolicyUpdateBrain *_scanPolicy;	// 72 = 0x48
    SUCoreMobileAsset *_maControl;	// 80 = 0x50
    SUCorePolicyUpdateBrain *_downloadPolicy;	// 88 = 0x58
    id <NRDUpdateDCoreDelegate> _delegate;	// 96 = 0x60
    NSNumber *_updateAttempt;	// 104 = 0x68
    id _brain;	// 112 = 0x70
    id _runningBrain;	// 120 = 0x78
    NSObject<OS_dispatch_queue> *_keyBagQueue;	// 128 = 0x80
    NSBackgroundActivityScheduler *_rescanScheduler;	// 136 = 0x88
    NSObject<OS_dispatch_queue> *_updateQueue;	// 144 = 0x90
    NSDictionary *_updateOptions;	// 152 = 0x98
}

- (void).cxx_destruct;	// IMP=0x000000010000e0ac
@property(retain, nonatomic) NSDictionary *updateOptions; // @synthesize updateOptions=_updateOptions;
@property _Bool forceBrainUpdate; // @synthesize forceBrainUpdate=_forceBrainUpdate;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *updateQueue; // @synthesize updateQueue=_updateQueue;
@property(retain, nonatomic) NSBackgroundActivityScheduler *rescanScheduler; // @synthesize rescanScheduler=_rescanScheduler;
@property int keyBagStateChangedNotifyToken; // @synthesize keyBagStateChangedNotifyToken=_keyBagStateChangedNotifyToken;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *keyBagQueue; // @synthesize keyBagQueue=_keyBagQueue;
@property(retain, nonatomic) id runningBrain; // @synthesize runningBrain=_runningBrain;
@property(retain, nonatomic) id brain; // @synthesize brain=_brain;
@property(retain, nonatomic) NSNumber *updateAttempt; // @synthesize updateAttempt=_updateAttempt;
@property(retain, nonatomic) id <NRDUpdateDCoreDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SUCorePolicyUpdateBrain *downloadPolicy; // @synthesize downloadPolicy=_downloadPolicy;
@property(retain, nonatomic) SUCoreMobileAsset *maControl; // @synthesize maControl=_maControl;
@property(retain, nonatomic) SUCorePolicyUpdateBrain *scanPolicy; // @synthesize scanPolicy=_scanPolicy;
@property(retain, nonatomic) SUCoreScan *scanner; // @synthesize scanner=_scanner;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(retain, nonatomic) MAAsset *localBrainAsset; // @synthesize localBrainAsset=_localBrainAsset;
@property(retain, nonatomic) MAAsset *updateBrainAsset; // @synthesize updateBrainAsset=_updateBrainAsset;
@property(retain, nonatomic) SUCoreFSM *updatedFSM; // @synthesize updatedFSM=_updatedFSM;
@property(retain, nonatomic) NSDictionary *stateTable; // @synthesize stateTable=_stateTable;
- (void)connectionInvalidated;	// IMP=0x000000010000de88
- (void)connectionInterrupted;	// IMP=0x000000010000dddc
- (void)newBrain:(id)arg1;	// IMP=0x000000010000dccc
- (void)newSchedulerWithIdentifier:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010000dbac
- (void)performUpdate:(id)arg1;	// IMP=0x000000010000d9b4
- (long long)performAction:(id)arg1 onEvent:(id)arg2 inState:(id)arg3 withInfo:(id)arg4 nextState:(id)arg5 error:(id *)arg6;	// IMP=0x000000010000d6dc
- (_Bool)isPasscodeLocked;	// IMP=0x000000010000d610
- (void)scheduleNRDUpdateBrainReScan:(_Bool)arg1;	// IMP=0x000000010000ce60
- (double)_minimumInterval:(double)arg1;	// IMP=0x000000010000cd84
- (long long)getSchedulerQOS;	// IMP=0x000000010000cb98
- (long long)actionUnknownAction:(id)arg1 error:(id *)arg2;	// IMP=0x000000010000cb24
- (long long)actionScheduleRetry:(id)arg1 error:(id *)arg2;	// IMP=0x000000010000c8dc
- (long long)actionRunBrain:(id *)arg1;	// IMP=0x000000010000c4a4
- (long long)actionLoadBrain:(id *)arg1;	// IMP=0x000000010000beac
- (long long)actionWaitForUnlock:(id *)arg1;	// IMP=0x000000010000bd3c
- (long long)actionCheckDeviceUnlockConstraint:(id *)arg1;	// IMP=0x000000010000b934
- (_Bool)brainLoadRequiresUnlock;	// IMP=0x000000010000b92c
- (void)maDownloadFailed:(id)arg1;	// IMP=0x000000010000b7b4
- (void)maDownloaded:(id)arg1;	// IMP=0x000000010000b6b8
- (void)maDownloadStalled:(id)arg1;	// IMP=0x000000010000b600
- (void)maDownloadProgress:(id)arg1;	// IMP=0x000000010000b548
- (long long)actionDownloadBrainUpdate:(id *)arg1;	// IMP=0x000000010000b148
- (long long)actionBeginBrainScan:(id *)arg1;	// IMP=0x000000010000aa34
- (void)cleanBeforeScan;	// IMP=0x000000010000a9f8
- (long long)actionLoadPersisted:(id *)arg1;	// IMP=0x000000010000a71c
- (void)cleanReScanScheduler;	// IMP=0x000000010000a594
- (id)findLocalBrainAsset;	// IMP=0x000000010000a13c
- (void)registerUpdatedFSMhandlers;	// IMP=0x0000000100009edc
- (Class)_infoClassForAction:(id)arg1;	// IMP=0x0000000100009e94
- (id)initWithDelegate:(id)arg1;	// IMP=0x0000000100009480

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

