//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, SUCoreProgress;

@protocol SUCoreMobileAssetDelegate <NSObject>

@optional
- (void)maAnomaly:(NSError *)arg1;
- (void)maAssetRemoveFailed:(NSError *)arg1;
- (void)maAssetRemoved;
- (void)maDownloadFailed:(NSError *)arg1;
- (void)maDownloaded:(SUCoreProgress *)arg1;
- (void)maDownloadStalled:(SUCoreProgress *)arg1;
- (void)maDownloadProgress:(SUCoreProgress *)arg1;
@end

