//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SAObjects/AceObject.h>

@interface AceObject (SRAdditions)
- (_Bool)sr_isUserUtterance;	// IMP=0x0000000100096470
- (_Bool)sr_isUtterance;	// IMP=0x0000000100096468
- (long long)sr_aceCommandType;	// IMP=0x0000000100096460
- (_Bool)sr_waitsForConfirmation;	// IMP=0x0000000100096730
- (_Bool)_afui_updateMapsAnalytics;	// IMP=0x0000000100096ac8
- (id)_afui_mapsRelatedChildren;	// IMP=0x0000000100096ac0
- (id)_afui_mapsRelatedChild;	// IMP=0x0000000100096ab8
@end

