//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SAObjects/SAGKSnippet.h>

@interface SAGKSnippet (Siriland)
- (id)sr_sirilandShim;	// IMP=0x0000000100097f54
- (_Bool)_isWikiSnippet;	// IMP=0x0000000100097e58
- (_Bool)_sr_objects:(id)arg1 matchClassOrder:(id)arg2;	// IMP=0x0000000100097c04
@end

