//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SRAnalyticsSupplement : NSObject
{
    NSString *_lastComputedRefId;	// 8 = 0x8
    int _lastComputedMode;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100048860
- (int)computedModeForRefId:(id)arg1;	// IMP=0x0000000100048824
- (void)didComputeMode:(int)arg1 forAceCommandWithRefId:(id)arg2;	// IMP=0x0000000100048814

@end

