//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class SRCarPlayFocusView, UILabel;

@interface SRStarkTableViewCell : UITableViewCell
{
    SRCarPlayFocusView *_focusView;	// 8 = 0x8
    _Bool _showFavoriteStar;	// 16 = 0x10
    UILabel *_secondaryLabel;	// 24 = 0x18
    UILabel *_tertiaryLabel;	// 32 = 0x20
}

+ (double)_tableViewCellVerticalEdgesBuffer;	// IMP=0x0000000100037448
+ (double)_tableViewCellHorizontalEdgesBuffer;	// IMP=0x0000000100037440
- (void).cxx_destruct;	// IMP=0x0000000100037a48
@property(nonatomic) _Bool showFavoriteStar; // @synthesize showFavoriteStar=_showFavoriteStar;
@property(readonly, nonatomic) UILabel *tertiaryLabel; // @synthesize tertiaryLabel=_tertiaryLabel;
@property(readonly, nonatomic) UILabel *secondaryLabel; // @synthesize secondaryLabel=_secondaryLabel;
- (void)_updateAccessoryViewForType:(long long)arg1 favorited:(_Bool)arg2;	// IMP=0x000000010003782c
- (void)_updateViewsForFocus:(_Bool)arg1 highlighted:(_Bool)arg2 selected:(_Bool)arg3 traitCollection:(id)arg4;	// IMP=0x00000001000374b8
- (void)layoutSubviews;	// IMP=0x0000000100036d98
- (void)updateConfigurationUsingState:(id)arg1;	// IMP=0x0000000100036cac
- (void)setAccessoryType:(long long)arg1;	// IMP=0x0000000100036bbc
- (_Bool)canBecomeFocused;	// IMP=0x0000000100036bb4
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x00000001000367d0

@end

