//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "UINavigationControllerDelegate-Protocol.h"

@class TVDANavigationController;

@protocol TVDANavigationControllerDelegate <UINavigationControllerDelegate>
- (void)navigationControllerDidComplete:(TVDANavigationController *)arg1;
@end

