//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TVDAMeasurable-Protocol.h"

@class NSMutableArray, NSString, NSTimer;
@protocol TVDAMeasurement;

@interface TVDAStepAction : NSObject <TVDAMeasurable>
{
    NSString *_title;	// 8 = 0x8
    long long _flow;	// 16 = 0x10
    double _idleSecondsToTrigger;	// 24 = 0x18
    NSMutableArray *_handlers;	// 32 = 0x20
    NSMutableArray *_timerStatusHandlers;	// 40 = 0x28
    NSTimer *_timer;	// 48 = 0x30
    id <TVDAMeasurement> _measurement;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x0000000100003368
@property(retain, nonatomic) id <TVDAMeasurement> measurement; // @synthesize measurement=_measurement;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) NSMutableArray *timerStatusHandlers; // @synthesize timerStatusHandlers=_timerStatusHandlers;
@property(retain, nonatomic) NSMutableArray *handlers; // @synthesize handlers=_handlers;
@property(nonatomic) double idleSecondsToTrigger; // @synthesize idleSecondsToTrigger=_idleSecondsToTrigger;
@property(readonly, nonatomic) long long flow; // @synthesize flow=_flow;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001000030e0
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100002e64
- (void)_destroyTimer;	// IMP=0x0000000100002e0c
- (void)forceRunHandlers;	// IMP=0x0000000100002ba0
- (void)resetTimer;	// IMP=0x0000000100002b6c
- (void)stopTimer;	// IMP=0x0000000100002b18
- (void)startTimer;	// IMP=0x0000000100002610
- (void)addSecondsToTriggerStatusHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001000025a8
- (void)addHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100002540
- (id)initWithTitle:(id)arg1 flow:(long long)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100002424
- (id)init;	// IMP=0x000000010000240c

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

