//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSMutableSet, NSOrderedSet, TMTimeZone;
@protocol TMTimeZoneManagerDelegate;

@interface TMTimeZoneManager : NSObject
{
    NSMutableDictionary *inputs;	// 8 = 0x8
    NSMutableSet *availableSources;	// 16 = 0x10
    NSOrderedSet *rules;	// 24 = 0x18
    TMTimeZone *_currentTimeZone;	// 32 = 0x20
    id <TMTimeZoneManagerDelegate> _delegate;	// 40 = 0x28
}

@property(nonatomic) id <TMTimeZoneManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain) TMTimeZone *currentTimeZone; // @synthesize currentTimeZone=_currentTimeZone;
- (id)description;	// IMP=0x00000001000113f8
- (_Bool)isSourceAvailable:(id)arg1;	// IMP=0x00000001000112d0
- (void)setSourceUnavailable:(id)arg1;	// IMP=0x0000000100011118
- (void)setSourceAvailable:(id)arg1;	// IMP=0x0000000100010f5c
- (id)initWithRules:(id)arg1 delegate:(id)arg2;	// IMP=0x0000000100010dcc
- (id)initWithRules:(id)arg1;	// IMP=0x0000000100010dbc
- (void)dealloc;	// IMP=0x0000000100010d50
- (void)reset:(id)arg1;	// IMP=0x0000000100010b8c
- (void)setSourceTimeZone:(id)arg1;	// IMP=0x0000000100010990

@end

