//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ManagedConfiguration/MCTunnelParser.h>

@class NSData, NSMutableDictionary, NSString;

@interface MCIPCUTunnelParser : MCTunnelParser
{
    CDUnknownBlockType _escalationBlock;	// 8 = 0x8
    NSMutableDictionary *_CSR;	// 16 = 0x10
    NSString *_hostIdentifier;	// 24 = 0x18
    NSData *_challengeCertificate;	// 32 = 0x20
    NSData *_challenge;	// 40 = 0x28
    long long _downloadAndApplyCloudConfigurationCommandRetryCount;	// 48 = 0x30
    long long _setCloudConfigurationCommandRetryCount;	// 56 = 0x38
}

+ (id)_certificatesFromCertificateDataArray:(id)arg1;	// IMP=0x0000000100006d68
- (void).cxx_destruct;	// IMP=0x0000000100008bcc
@property(nonatomic) long long setCloudConfigurationCommandRetryCount; // @synthesize setCloudConfigurationCommandRetryCount=_setCloudConfigurationCommandRetryCount;
@property(nonatomic) long long downloadAndApplyCloudConfigurationCommandRetryCount; // @synthesize downloadAndApplyCloudConfigurationCommandRetryCount=_downloadAndApplyCloudConfigurationCommandRetryCount;
@property(retain, nonatomic) NSData *challenge; // @synthesize challenge=_challenge;
@property(retain, nonatomic) NSData *challengeCertificate; // @synthesize challengeCertificate=_challengeCertificate;
@property(retain, nonatomic) NSString *hostIdentifier; // @synthesize hostIdentifier=_hostIdentifier;
@property(retain, nonatomic) NSMutableDictionary *CSR; // @synthesize CSR=_CSR;
@property(copy, nonatomic) CDUnknownBlockType escalationBlock; // @synthesize escalationBlock=_escalationBlock;
- (void)processRequest:(id)arg1 assertion:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x0000000100008414
- (id)_commandSetWiFiPower:(id)arg1;	// IMP=0x0000000100008054
- (void)_commandEstablishProvisionalEnrollmentRequest:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100007b5c
- (void)_commandEscalateResponse:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100007748
- (void)_commandEscalate:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x00000001000074e0
- (void)_commandEraseDevice:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100007130
- (void)_commandPollMDMIfNetworkTetheredRequest:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100006f54
- (void)_commandDownloadAndApplyCloudConfiguration:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100005ce4
- (_Bool)_isXPCInterruptionError:(id)arg1;	// IMP=0x0000000100005c4c
- (id)_configuratorCloudConfigurationErrorWithCloudConfigDetails:(id)arg1 error:(id)arg2;	// IMP=0x0000000100005bbc
- (id)_configuratorProvisionalEnrollmentErrorWithDetails:(id)arg1 error:(id)arg2;	// IMP=0x0000000100005b2c
- (id)_underlyingCloudConfigErrorFromError:(id)arg1;	// IMP=0x0000000100005a54
- (void)_commandSetCloudConfiguration:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100005570
- (void)_commandGetCloudConfiguration:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100005490
- (void)_commandGetStoredProfile:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100005214
- (id)_commandStoreProfile:(id)arg1;	// IMP=0x0000000100004db0
- (id)_commandInstallProfile:(id)arg1;	// IMP=0x0000000100004a14
- (id)_commandSetCertificate:(id)arg1;	// IMP=0x000000010000471c
- (id)_commandRemoveProfile:(id)arg1;	// IMP=0x0000000100004174
- (id)_commandGetProfileList:(id)arg1;	// IMP=0x0000000100003c48
- (id)_commandGetEncryptionKey:(id)arg1;	// IMP=0x0000000100003918
- (id)_commandHello:(id)arg1;	// IMP=0x00000001000038f8
- (id)_commandFlush:(id)arg1;	// IMP=0x0000000100003838
- (id)init;	// IMP=0x00000001000037e8

@end

