//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RadioCC.h"

@interface RadioPowerCC : RadioCC
{
}

- (void)defaultAction;	// IMP=0x000000010002fc5c
- (unsigned long long)convertDetailStringToValue:(struct __CFString *)arg1;	// IMP=0x000000010002fbb8
- (id)initWithRunLoopAndParams:(struct __CFRunLoop *)arg1 withMitigationType:(int)arg2 withParams:(struct __CFDictionary *)arg3;	// IMP=0x000000010002fa48

@end

