//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIFont.h>

@interface UIFont (TVSystemBulletinService)
- (id)tvsb_fontWithWeight:(double)arg1;	// IMP=0x0000000100004790
@end

