/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 27, 2020 at 12:50:25 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18J386)
* Image Source: /usr/lib/swift/libswiftNetwork.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface Network._NWListener : _UKNOWN_SUPERCLASS_ {

	 _newConnectionHandler;
	 _state;
	 nw;
	 _stateUpdateHandler;
	 parameters;
	 _service;
	 _serviceRegistrationUpdateHandler;
	 _queue;

}
@end

