/*
* This header is generated by classdump-dyld 1.0
* on Saturday, September 26, 2020 at 1:13:43 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18J386)
* Image Source: /usr/lib/libtzupdate.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class TZFileSystemInterface, NSXPCConnection;

@interface TZUpdate : NSObject {

	TZFileSystemInterface* _fileSystemInterface;
	NSXPCConnection* _connectionToService;

}

@property (retain) TZFileSystemInterface * fileSystemInterface;              //@synthesize fileSystemInterface=_fileSystemInterface - In the implementation block
@property (retain) NSXPCConnection * connectionToService;                    //@synthesize connectionToService=_connectionToService - In the implementation block
+(id)sharedInstance;
-(id)init;
-(id)createNewXPCConnection;
-(BOOL)isUpdateWaiting;
-(TZFileSystemInterface *)fileSystemInterface;
-(void)isUpdateWaitingWithCompletion:(/*^block*/id)arg1 ;
-(void)purgeAllAssetsWithCompletion:(/*^block*/id)arg1 ;
-(id)affectedZones;
-(id)currentTZDataVersion;
-(BOOL)alertForAllZones;
-(id)updateTZDataVersion;
-(void)setFileSystemInterface:(TZFileSystemInterface *)arg1 ;
-(NSXPCConnection *)connectionToService;
-(void)setConnectionToService:(NSXPCConnection *)arg1 ;
@end

