//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MCMCommand.h"

@interface MCMCommandRepairUserData : MCMCommand
{
}

+ (Class)incomingMessageClass;	// IMP=0x000000010007cf44
+ (unsigned long long)command;	// IMP=0x000000010007cf3c
- (_Bool)fromQueue:(id)arg1 executeWithError:(unsigned long long *)arg2;	// IMP=0x000000010007cf50

@end

