//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString, NSURL;

@interface MCMPOSIXUser : NSObject <NSCopying>
{
    _Bool _root;	// 8 = 0x8
    _Bool _roleUser;	// 9 = 0x9
    unsigned int _UID;	// 12 = 0xc
    unsigned int _primaryGID;	// 16 = 0x10
    NSURL *_homeDirectoryURL;	// 24 = 0x18
    NSString *_name;	// 32 = 0x20
}

+ (id)_getCachedUID:(unsigned int)arg1 flush:(_Bool)arg2 onCacheMiss:(CDUnknownBlockType)arg3;	// IMP=0x0000000100082780
+ (id)_posixUserWithPasswdPtr:(struct passwd *)arg1;	// IMP=0x000000010008253c
+ (id)_posixUserWithPasswdFillBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000100082350
+ (void)flush;	// IMP=0x0000000100082324
+ (id)root;	// IMP=0x0000000100082314
+ (id)nobody;	// IMP=0x0000000100082304
+ (id)posixUserWithUID:(unsigned int)arg1;	// IMP=0x00000001000821d4
+ (id)posixUserWithName:(id)arg1;	// IMP=0x0000000100082080
+ (id)currentPOSIXUser;	// IMP=0x0000000100082050
- (void).cxx_destruct;	// IMP=0x0000000100082020
@property(readonly, nonatomic, getter=isRoleUser) _Bool roleUser; // @synthesize roleUser=_roleUser;
@property(readonly, nonatomic, getter=isRoot) _Bool root; // @synthesize root=_root;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) NSURL *homeDirectoryURL; // @synthesize homeDirectoryURL=_homeDirectoryURL;
@property(readonly, nonatomic) unsigned int primaryGID; // @synthesize primaryGID=_primaryGID;
@property(readonly, nonatomic) unsigned int UID; // @synthesize UID=_UID;
- (id)initWithUID:(unsigned int)arg1 primaryGID:(unsigned int)arg2 homeDirectoryURL:(id)arg3 name:(id)arg4;	// IMP=0x0000000100081f10
- (_Bool)_isRoleUserWithUID:(unsigned int)arg1 homeDirectoryURL:(id)arg2;	// IMP=0x0000000100081f04
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100081e48
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100081dcc
- (_Bool)isEqualToPOSIXUser:(id)arg1;	// IMP=0x0000000100081db8
- (unsigned long long)hash;	// IMP=0x0000000100081db0
- (id)fullDescription;	// IMP=0x0000000100081c8c
- (id)description;	// IMP=0x0000000100081ba8

@end

