//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MSUiBootHeader.h"

@interface MSUiBootHeaderV1 : MSUiBootHeader
{
    unsigned int _valid;	// 32 = 0x20
}

@property unsigned int valid; // @synthesize valid=_valid;
- (long long)compareTo:(id)arg1;	// IMP=0x0000000100030634
- (_Bool)isValid;	// IMP=0x00000001000305e4
- (id)description;	// IMP=0x0000000100030540
- (unsigned int)length;	// IMP=0x0000000100030538
- (void)makeValid;	// IMP=0x0000000100030528
- (void)setAsFirstGeneration;	// IMP=0x0000000100030518
- (void)invalidate;	// IMP=0x0000000100030508
- (_Bool)loadHeaderAtOffset:(unsigned int)arg1;	// IMP=0x0000000100030458
- (id)packStructure;	// IMP=0x00000001000303f4

@end

