//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UINavigationController.h>

@class MISSING_TYPE;

@interface _TtC8AppStore24FlowNavigationController : UINavigationController
{
    MISSING_TYPE *flowController;	// 8 = 0x8
    MISSING_TYPE *actionRunner;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x0000000100078204
- (id)initWithRootViewController:(id)arg1;	// IMP=0x0000000100078244
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100077d90
- (id)init;	// IMP=0x0000000100077d7c
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100077cf8
- (id)initWithNavigationBarClass:(Class)arg1 toolbarClass:(Class)arg2;	// IMP=0x0000000100077c98

@end

