//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE, _TtC8AppStore11ArtworkView, _TtC8AppStore16DynamicTypeLabel;

@interface _TtC8AppStore15SmallLockupView : UIView
{
    MISSING_TYPE *artworkView;	// 8 = 0x8
    MISSING_TYPE *titleLabel;	// 16 = 0x10
    MISSING_TYPE *subtitleLabel;	// 24 = 0x18
    MISSING_TYPE *metrics;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0000000100091298
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *accessibilitySubtitleLabel;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *accessibilityTitleLabel;
@property(nonatomic, readonly) _TtC8AppStore11ArtworkView *accessibilityArtworkView;
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100091164
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x0000000100090ff4
- (void)layoutSubviews;	// IMP=0x0000000100090fc8
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100090d40
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100090d20

@end

