//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC8AppStore17RoundedCornerView.h"

@class MISSING_TYPE;

@interface _TtC8AppStore9VideoView : _TtC8AppStore17RoundedCornerView
{
    MISSING_TYPE *previewFrameArtwork;	// 56 = 0x38
    MISSING_TYPE *videoPlayer;	// 64 = 0x40
    MISSING_TYPE *playerViewController;	// 72 = 0x48
    MISSING_TYPE *templateMediaEvent;	// 0 = 0x0
    MISSING_TYPE *templateClickEvent;	// 0 = 0x0
    MISSING_TYPE *metricsPipeline;	// 0 = 0x0
    MISSING_TYPE *container;	// 0 = 0x0
    MISSING_TYPE *videoUrl;	// 0 = 0x0
    MISSING_TYPE *interactionState;	// 0 = 0x0
    MISSING_TYPE *playbackId;	// 0 = 0x0
    MISSING_TYPE *delegate;	// 0 = 0x0
    MISSING_TYPE *isFullScreen;	// 0 = 0x0
    MISSING_TYPE *isTransitioningToFullscreen;	// 0 = 0x0
    MISSING_TYPE *configuration;	// 0 = 0x0
    MISSING_TYPE *fullScreenVideoController;	// 0 = 0x0
    MISSING_TYPE *fullScreenTransitionManager;	// 0 = 0x0
    MISSING_TYPE *wasAudioOnPreFullScreen;	// 0 = 0x0
    MISSING_TYPE *playWorkItem;	// 0 = 0x0
    MISSING_TYPE *releaseAssetsAtNextPauseState;	// 0 = 0x0
}

- (void).cxx_destruct;	// IMP=0x00000001000faf00
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000fe4f8
- (void)willExitIdleMode;	// IMP=0x00000001000fe4cc
- (void)willEnterIdleMode;	// IMP=0x00000001000fe3ac
- (void)handleMediaServicesReset;	// IMP=0x00000001000fe380
- (void)_setContinuousCornerRadius:(double)arg1;	// IMP=0x00000001000fe0ac
@property(nonatomic) double _continuousCornerRadius;
- (void)_setCornerRadius:(double)arg1;	// IMP=0x00000001000fe018
@property(nonatomic) double _cornerRadius;
- (void)updateAudioSessionCategoryWithIsAudioOn:(_Bool)arg1;	// IMP=0x00000001000fdbb8
- (void)layoutSubviews;	// IMP=0x00000001000fc6c8
- (void)didChangeAutoPlayVideoSetting;	// IMP=0x00000001000fc180
- (void)dealloc;	// IMP=0x00000001000fae5c
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000fac80

@end

