//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC8AppStore22BaseCollectionViewCell.h"

@class MISSING_TYPE, NSArray, _TtC8AppStore16DynamicTypeLabel;

@interface _TtC8AppStore28AnnotationCollectionViewCell : _TtC8AppStore22BaseCollectionViewCell
{
    MISSING_TYPE *titleLabel;	// 176 = 0xb0
    MISSING_TYPE *summaryLabel;	// 184 = 0xb8
    MISSING_TYPE *detailViewPool;	// 0 = 0x0
    MISSING_TYPE *detailViews;	// 0 = 0x0
    MISSING_TYPE *linkLabel;	// 0 = 0x0
    MISSING_TYPE *backgroundEffectView;	// 0 = 0x0
    MISSING_TYPE *isExpanded;	// 0 = 0x0
    MISSING_TYPE *titleText;	// 0 = 0x0
    MISSING_TYPE *explicitSummary;	// 0 = 0x0
    MISSING_TYPE *detailItems;	// 0 = 0x0
    MISSING_TYPE *linkAction;	// 0 = 0x0
}

- (void).cxx_destruct;	// IMP=0x000000010015639c
- (void)accessibilityLinkLabelTapped;	// IMP=0x0000000100156264
@property(nonatomic, readonly) _Bool accessibilityIsSummaryExpandable;
@property(nonatomic, readonly) _Bool accessibilityCellIsExpanded;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *accessibilityLinkLabel;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *accessibilitySummaryLabel;
@property(nonatomic, readonly) _TtC8AppStore16DynamicTypeLabel *accessibilityTitleLabel;
@property(nonatomic, readonly) NSArray *accessibilityDetailItems;
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x0000000100155330
- (void)layoutSubviews;	// IMP=0x0000000100154714
- (struct JUMeasurements)measurementsWithFitting:(struct CGSize)arg1 in:(id)arg2;	// IMP=0x0000000100154284
@property(nonatomic, readonly) _Bool canBecomeFocused;
- (void)prepareForReuse;	// IMP=0x0000000100153ff0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100153e18
@property(nonatomic) long long overrideUserInterfaceStyle;

@end

