//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class MISSING_TYPE;

@interface _TtC8AppStore20ReviewsContainerCell : UICollectionViewCell
{
    MISSING_TYPE *rateButtonView;	// 8 = 0x8
    MISSING_TYPE *summaryView;	// 16 = 0x10
    MISSING_TYPE *histogramView;	// 24 = 0x18
    MISSING_TYPE *noRatingsView;	// 32 = 0x20
    MISSING_TYPE *pageTraits;	// 40 = 0x28
    MISSING_TYPE *scrollCoordinator;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x000000010019ff30
@property(nonatomic, readonly) _Bool canBecomeFocused;
- (void)prepareForReuse;	// IMP=0x000000010019fad4
- (void)layoutSubviews;	// IMP=0x000000010019f918
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010019f604
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010019f5e4

@end

