//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC8AppStore17AccountSignInView : UIView
{
    MISSING_TYPE *didSelectHandler;	// 8 = 0x8
    MISSING_TYPE *iconView;	// 24 = 0x18
    MISSING_TYPE *signInButton;	// 32 = 0x20
    MISSING_TYPE *subTextLabel;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0000000100088234
- (void)didSelectSignIn:(id)arg1;	// IMP=0x0000000100088164
@property(nonatomic, readonly) _Bool canBecomeFocused;
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010008808c
- (struct JUMeasurements)measurementsWithFitting:(struct CGSize)arg1 in:(id)arg2;	// IMP=0x0000000100088000
- (void)layoutSubviews;	// IMP=0x0000000100087e68
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100087ac4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100087aa4

@end

