//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MISSING_TYPE;

@interface _TtC8AppStore27ArcadeWelcomeViewController : UIViewController
{
    MISSING_TYPE *objectGraph;	// 8 = 0x8
    MISSING_TYPE *presenter;	// 16 = 0x10
    MISSING_TYPE *artworkLoader;	// 24 = 0x18
    MISSING_TYPE *lifecycleObserver;	// 32 = 0x20
    MISSING_TYPE *impressionsCalculator;	// 72 = 0x48
    MISSING_TYPE *pageView;	// 80 = 0x50
    MISSING_TYPE *overlayView;	// 88 = 0x58
}

- (void).cxx_destruct;	// IMP=0x000000010014e598
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010014e530
- (void)appExitedWhileAppeared;	// IMP=0x000000010014e2cc
- (void)appEnteredWhileAppeared;	// IMP=0x000000010014e2c4
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x000000010014e230
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x000000010014e1f4
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010014dfc8
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010014dd24
- (void)viewDidLoad;	// IMP=0x000000010014dcf8
- (void)viewWillLayoutSubviews;	// IMP=0x000000010014dbac
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010014d950

@end

