//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC8AppStore18ArtworkOverlayView : UIView
{
    MISSING_TYPE *metrics;	// 8 = 0x8
    MISSING_TYPE *pillView;	// 40 = 0x28
    MISSING_TYPE *avatarShowcase;	// 48 = 0x30
    MISSING_TYPE *placeAvatarShowcaseBlock;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x000000010011deb0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010011defc
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010011de78
- (void)layoutSubviews;	// IMP=0x000000010011ddd0
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010011dd78

@end

