//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC8AppStore22BaseCollectionViewCell.h"

@class MISSING_TYPE, UILabel;

@interface _TtC8AppStore21ProductCapabilityCell : _TtC8AppStore22BaseCollectionViewCell
{
    MISSING_TYPE *iconImageView;	// 176 = 0xb0
    MISSING_TYPE *titleLabel;	// 184 = 0xb8
    MISSING_TYPE *captionLabel;	// 192 = 0xc0
}

- (void).cxx_destruct;	// IMP=0x00000001000d281c
@property(nonatomic, readonly) UILabel *accessibilityCaptionLabel;
@property(nonatomic, readonly) UILabel *accessibilityTitleLabel;
- (void)prepareForReuse;	// IMP=0x00000001000d26e8
- (void)layoutSubviews;	// IMP=0x00000001000d257c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000d22f8

@end

