//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITapGestureRecognizer.h>

@class MISSING_TYPE;

@interface _TtC8AppStore26TapActionGestureRecognizer : UITapGestureRecognizer
{
    MISSING_TYPE *action;	// 8 = 0x8
    MISSING_TYPE *actionTrampoline;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00000001000d4a2c
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;	// IMP=0x00000001000d4998
- (void)execute;	// IMP=0x00000001000d496c

@end

