//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC8AppStore25ZoomTransitioningDelegate : NSObject
{
}

- (id)init;	// IMP=0x000000010018fad8
- (id)animationControllerForDismissedController:(id)arg1;	// IMP=0x000000010018fa3c
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;	// IMP=0x000000010018f96c

@end

