//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewFlowLayout.h>

@class MISSING_TYPE;

@interface _TtC8AppStore25ShelfDisplayingFlowLayout : UICollectionViewFlowLayout
{
    MISSING_TYPE *multiColumnMinYBySection;	// 8 = 0x8
    MISSING_TYPE *multiColumnOrigins;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010003225c
- (id)invalidationContextForBoundsChange:(struct CGRect)arg1;	// IMP=0x0000000100031510
- (_Bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect)arg1;	// IMP=0x00000001000312e0
- (id)layoutAttributesForDecorationViewOfKind:(id)arg1 atIndexPath:(id)arg2;	// IMP=0x0000000100031114
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;	// IMP=0x0000000100031064
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;	// IMP=0x0000000100030e80
- (void)prepareLayout;	// IMP=0x00000001000307dc
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000306ec
- (id)init;	// IMP=0x00000001000306cc

@end

