//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC8AppStore22BaseCollectionViewCell.h"

@class MISSING_TYPE, UILabel;

@interface _TtC8AppStore29ProductRatingsSummaryCardView : _TtC8AppStore22BaseCollectionViewCell
{
    MISSING_TYPE *ratingLabel;	// 176 = 0xb0
    MISSING_TYPE *outOfRatingLabel;	// 184 = 0xb8
    MISSING_TYPE *starRatingView;	// 192 = 0xc0
}

- (void).cxx_destruct;	// IMP=0x000000010003ed5c
@property(nonatomic, readonly) UILabel *accessibilityCurrentRatingLabel;
- (id)_preferredConfigurationForFocusAnimation:(long long)arg1 inContext:(id)arg2;	// IMP=0x000000010003e69c
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010003e570
- (void)layoutSubviews;	// IMP=0x000000010003e544
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010003df74

@end

