//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface CDDPaths : NSObject
{
}

+ (id)duetBMAssetConfigPath;	// IMP=0x00000001000224dc
+ (id)duetBMConfigPath;	// IMP=0x00000001000224d0
+ (const char *)crashReporterDirectory;	// IMP=0x00000001000224c4
+ (const char *)crashReporterDatabaseLocation;	// IMP=0x00000001000224b8
+ (id)taskAssetDirectoryInstall;	// IMP=0x00000001000224ac
+ (id)taskAssetDirectory;	// IMP=0x00000001000224a0
+ (id)taskAssetDuetDirectoryInstall;	// IMP=0x0000000100022494
+ (id)taskAssetDuetDirectory;	// IMP=0x0000000100022488
+ (id)userLocalKnowledgeDatabaseDirectory;	// IMP=0x0000000100022398
+ (id)peopleDatabaseDirectory;	// IMP=0x00000001000222a8
+ (id)knowledgeDatabaseDirectory;	// IMP=0x00000001000221b8
+ (id)CDDConfigurationBundlePath;	// IMP=0x0000000100022154
+ (id)CDDClassDBackupDatabasePath;	// IMP=0x00000001000220f0
+ (id)CDDClassDDatabasePath;	// IMP=0x000000010002208c
+ (id)CDDClassADatabasePath;	// IMP=0x0000000100022028
+ (id)CDDDatabasePath;	// IMP=0x0000000100021fc4
+ (id)CDDConfigurationBundlePathDefault;	// IMP=0x0000000100021fb8
+ (id)CDDUserDatabaseDirectory;	// IMP=0x0000000100021fac
+ (id)CDDDatabaseDirectory;	// IMP=0x0000000100021fa0
+ (id)simulatorSharedPathFor:(id)arg1;	// IMP=0x0000000100021ed4
+ (id)simulatorHomePathFor:(id)arg1;	// IMP=0x0000000100021e68
+ (id)simulatorSystemPathFor:(id)arg1 withEnvVar:(id)arg2;	// IMP=0x0000000100021d7c

@end

