//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface NDFileUtilities : NSObject
{
}

+ (_Bool)itemShouldBePurged:(id)arg1;	// IMP=0x0000000100035afc
+ (void)markItemAsPurged:(id)arg1;	// IMP=0x0000000100035a68
+ (id)fetchStreamingZipModificationDate:(id)arg1;	// IMP=0x00000001000359a8
+ (void)removeStreamingZipModificationDate:(id)arg1;	// IMP=0x0000000100035944
+ (void)updateStreamingZipModificationDate:(id)arg1;	// IMP=0x00000001000358a4
+ (void)setDaemonWorkState:(_Bool)arg1;	// IMP=0x00000001000356ec
+ (id)defaultDownloadDirectoryForBundleID:(id)arg1;	// IMP=0x0000000100035644
+ (id)defaultDownloadDirectoryContainer;	// IMP=0x0000000100035424
+ (void)createDirectoryAtURL:(id)arg1;	// IMP=0x0000000100035298
+ (void)createDirectoryAtPath:(id)arg1;	// IMP=0x000000010003510c
+ (_Bool)createDataVaultDirectoryAtPath:(id)arg1;	// IMP=0x0000000100034c80
+ (void)removeItemAtURL:(id)arg1;	// IMP=0x0000000100034afc
+ (void)removeItemAtPath:(id)arg1;	// IMP=0x0000000100034978
+ (id)nsurlsessiondLaunchdPath;	// IMP=0x00000001000348fc
+ (id)sessionPath:(id)arg1 forBundleID:(id)arg2;	// IMP=0x0000000100034814
+ (id)bundleManagerPath:(id)arg1;	// IMP=0x0000000100034734
+ (id)nsurlsessiondPath;	// IMP=0x0000000100034680

@end

