//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class PDURLSessionProxyTaskMessage;

@interface PDURLSessionProxySetTaskPriority : PBCodable <NSCopying>
{
    unsigned int _priority;	// 8 = 0x8
    PDURLSessionProxyTaskMessage *_task;	// 16 = 0x10
    struct {
        unsigned int priority:1;
    } _has;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010000a6dc
@property(nonatomic) unsigned int priority; // @synthesize priority=_priority;
@property(retain, nonatomic) PDURLSessionProxyTaskMessage *task; // @synthesize task=_task;
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010000a618
- (unsigned long long)hash;	// IMP=0x000000010000a5b0
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010000a4d4
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010000a42c
- (void)copyTo:(id)arg1;	// IMP=0x000000010000a3b4
- (void)writeTo:(id)arg1;	// IMP=0x000000010000a344
- (_Bool)readFrom:(id)arg1;	// IMP=0x000000010000a0a4
- (id)dictionaryRepresentation;	// IMP=0x0000000100009fb4
- (id)description;	// IMP=0x0000000100009f00
@property(nonatomic) _Bool hasPriority;
@property(readonly, nonatomic) _Bool hasTask;

@end

