/*
* This header is generated by classdump-dyld 1.0
* on Saturday, September 26, 2020 at 1:36:33 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18J386)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <CoreData/NSManagedObject.h>

@class NSString, NSNumber, NSSet;

@interface RTEventLocationIdentifierMO : NSManagedObject

@property (nonatomic,retain) NSString * name; 
@property (nonatomic,retain) NSNumber * source; 
@property (nonatomic,retain) NSString * calendarIdentifier; 
@property (nonatomic,retain) NSSet * loiHistogramItems; 
+(id)managedObjectWithEventLocationIdentifier:(id)arg1 inManagedObjectContext:(id)arg2 ;
@end

