//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol TVCacheDeletePurging <NSObject>
- (long long)purgeAmount:(long long)arg1 withUrgency:(long long)arg2;
- (long long)purgeableAmountWithUrgency:(long long)arg1;

@optional
- (void)cancelPurge;
@end

