//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class HBAppInfoController, NSSet, PBSAppInfoConfiguration;

@protocol HBAppInfoControllerDelegate <NSObject>
- (void)appInfoController:(HBAppInfoController *)arg1 didUpdateConfiguration:(PBSAppInfoConfiguration *)arg2;
- (void)appInfoController:(HBAppInfoController *)arg1 didUpdateAlternateAppIconsForAppInfos:(NSSet *)arg2;
- (void)appInfoController:(HBAppInfoController *)arg1 didRemoveAppInfos:(NSSet *)arg2;
- (void)appInfoController:(HBAppInfoController *)arg1 didAddAppInfos:(NSSet *)arg2;
@end

