//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface HBCloudSyncDeviceToCloudSyncUtility : NSObject
{
}

+ (id)_appIdsFromRootFolder:(id)arg1;	// IMP=0x000000010006cfc4
+ (_Bool)parentFolderForApp:(id)arg1 containsOnlyNonRestorableApps:(id)arg2;	// IMP=0x000000010006cd30
+ (_Bool)hasAllParametersForInstallation:(id)arg1;	// IMP=0x000000010006cb34
+ (_Bool)isFolderSyncable:(id)arg1;	// IMP=0x000000010006c8d0
+ (_Bool)isAppSyncable:(id)arg1;	// IMP=0x000000010006c4f0
+ (id)validateFolderStructureAndDiscardUnwantedItems:(id)arg1;	// IMP=0x000000010006bf70
+ (id)appsWithChangedAlternateAppIconsFromAllApps:(id)arg1 appIdsToSyncedIconNames:(id)arg2;	// IMP=0x000000010006bba0
+ (id)updateItemOrderIdsForMovedItemsInFolder:(id)arg1 baseOrderId:(double)arg2;	// IMP=0x000000010006b668
+ (id)updateItemOrderIdsForMovedItemsInFolder:(id)arg1;	// IMP=0x000000010006b654
+ (id)indicesForUnarrangedItemsInFolder:(id)arg1 subfolder:(CDUnknownBlockType)arg2;	// IMP=0x000000010006b1dc
+ (id)allItemsWithUpdatedOrderIdsFromFolder:(id)arg1 baseOrderId:(unsigned long long)arg2;	// IMP=0x000000010006af40
+ (_Bool)needToResetOrderingForItemsInFolder:(id)arg1;	// IMP=0x000000010006ab78
+ (_Bool)doItemOrderIdsCollideInFolder:(id)arg1;	// IMP=0x000000010006a9ac
+ (id)deletedItemsListFromFolder:(id)arg1 itemsToParentMapping:(id)arg2;	// IMP=0x000000010006a794
+ (id)addedOrModifiedItemsFromRootFolderItems:(id)arg1 currentParentFolderLevel:(long long)arg2 itemsToParentMapping:(id)arg3;	// IMP=0x000000010006a0ec
+ (id)foldersWithChangedDisplayNamesFromFolder:(id)arg1 folderIdentifiersMappedToDisplayNames:(id)arg2;	// IMP=0x0000000100069e90
+ (id)folderIdentifiersMappedToDisplayNamesFromSyncedRecords:(id)arg1 existingMapping:(id)arg2;	// IMP=0x0000000100069b90
+ (id)folderIdentifiersMappedToDisplayNames:(id)arg1;	// IMP=0x0000000100069994
+ (id)itemsToParentMappingFromItems:(id)arg1 currentFolderLevelIndex:(long long)arg2;	// IMP=0x00000001000695cc
+ (id)itemsToParentMappingFromAddedRecords:(id)arg1 deletedRecordIDs:(id)arg2 existingItemsToParentMapping:(id)arg3 rootFolder:(id)arg4;	// IMP=0x0000000100069148
+ (void)initialize;	// IMP=0x00000001000690e4

@end

