//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface HBCollectionComparator : NSObject
{
}

- (id)changesFromObjects:(id)arg1 toObjects:(id)arg2 withIdentifierBlock:(CDUnknownBlockType)arg3;	// IMP=0x0000000100077fc8
- (id)_changeForInsertingObjectsIntoCollection:(id)arg1 availableInCollection:(id)arg2;	// IMP=0x0000000100077de8
- (id)_changeForRemovingObjectsFromCollection:(id)arg1 missingFromCollection:(id)arg2;	// IMP=0x0000000100077c08

@end

