//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "HBUIFocusHiding-Protocol.h"

@class NSArray, NSString, UIColor, UIFont, UILabel, UIMotionEffectGroup, UIView, _TVImageStackView, _UIStackedImageConfiguration, _UIStackedImageContainerView;
@protocol UIFocusEnvironment, UIFocusItemContainer;

@interface HBImageStackCollectionViewCell : UICollectionViewCell <HBUIFocusHiding>
{
    _Bool _layoutIsDrawingFocused;	// 8 = 0x8
    UIMotionEffectGroup *_motionEffectGroup;	// 16 = 0x10
    _Bool _pressIsAnimating;	// 24 = 0x18
    _Bool _preventUnpress;	// 25 = 0x19
    double _titleHeight;	// 32 = 0x20
    double _titleWidthForAccessory;	// 40 = 0x28
    _Bool _unpressIsAnimating;	// 48 = 0x30
    _Bool _unpressOnEndAnimating;	// 49 = 0x31
    _Bool _alwaysDisplaysTitle;	// 50 = 0x32
    _Bool _showsPersistentFocus;	// 51 = 0x33
    _Bool _centeredImageStackWithoutResize;	// 52 = 0x34
    _Bool _holdsPress;	// 53 = 0x35
    _Bool _titleHidden;	// 54 = 0x36
    _UIStackedImageContainerView *_layeredImageView;	// 56 = 0x38
    _TVImageStackView *_imageStackView;	// 64 = 0x40
    NSString *_title;	// 72 = 0x48
    double _titleSpacing;	// 80 = 0x50
    long long _selectionStyle;	// 88 = 0x58
    UIView *_titleAccessoryView;	// 96 = 0x60
    UIView *_overlayView;	// 104 = 0x68
    UILabel *_titleLabel;	// 112 = 0x70
    UIColor *_textColor;	// 120 = 0x78
    UIFont *_titleFont;	// 128 = 0x80
    UIColor *_highlightedTextColor;	// 136 = 0x88
    UIColor *_unhighlightedTextColor;	// 144 = 0x90
    struct CGPoint _focusDirection;	// 152 = 0x98
}

+ (id)_titleHeightCache;	// IMP=0x0000000100061670
+ (struct CGSize)_scaledSizeForSize:(struct CGSize)arg1 sizeIncreaseOffset:(double)arg2;	// IMP=0x000000010005f570
- (void).cxx_destruct;	// IMP=0x000000010006220c
@property(nonatomic, getter=_isTitleHidden, setter=_setTitleHidden:) _Bool titleHidden; // @synthesize titleHidden=_titleHidden;
@property(nonatomic, getter=_holdsPress, setter=_setHoldsPress:) _Bool holdsPress; // @synthesize holdsPress=_holdsPress;
@property(nonatomic, getter=_focusDirection, setter=_setFocusDirection:) struct CGPoint focusDirection; // @synthesize focusDirection=_focusDirection;
@property(retain, nonatomic) UIColor *unhighlightedTextColor; // @synthesize unhighlightedTextColor=_unhighlightedTextColor;
@property(retain, nonatomic) UIColor *highlightedTextColor; // @synthesize highlightedTextColor=_highlightedTextColor;
@property(retain, nonatomic) UIFont *titleFont; // @synthesize titleFont=_titleFont;
@property(readonly, nonatomic, getter=_textColor) UIColor *textColor; // @synthesize textColor=_textColor;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic, getter=_centeredImageStackWithoutResize, setter=_setCenteredImageStackWithoutResize:) _Bool centeredImageStackWithoutResize; // @synthesize centeredImageStackWithoutResize=_centeredImageStackWithoutResize;
@property(nonatomic) _Bool showsPersistentFocus; // @synthesize showsPersistentFocus=_showsPersistentFocus;
@property(readonly, nonatomic) UIView *overlayView; // @synthesize overlayView=_overlayView;
@property(nonatomic) _Bool alwaysDisplaysTitle; // @synthesize alwaysDisplaysTitle=_alwaysDisplaysTitle;
@property(retain, nonatomic) UIView *titleAccessoryView; // @synthesize titleAccessoryView=_titleAccessoryView;
@property(nonatomic) long long selectionStyle; // @synthesize selectionStyle=_selectionStyle;
@property(nonatomic) double titleSpacing; // @synthesize titleSpacing=_titleSpacing;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) _TVImageStackView *imageStackView; // @synthesize imageStackView=_imageStackView;
@property(retain, nonatomic) _UIStackedImageContainerView *layeredImageView; // @synthesize layeredImageView=_layeredImageView;
- (_Bool)shouldHideFocusForReasons:(unsigned long long)arg1;	// IMP=0x00000001000620d0
- (void)_updateTitleLabelContentScaleFactor;	// IMP=0x0000000100062074
- (void)_updateTitleLabelFont;	// IMP=0x0000000100061f5c
- (void)_updateTitleShadowForFocus:(_Bool)arg1;	// IMP=0x0000000100061dcc
- (void)_updateTitleTextColorForFocus:(_Bool)arg1;	// IMP=0x0000000100061d78
- (void)_updateTitleLayerAlphas;	// IMP=0x0000000100061c9c
- (void)_updateTitleLayers;	// IMP=0x0000000100061a30
- (void)_updateTitleWidthAndHeight;	// IMP=0x0000000100061898
- (void)_updateTitleWidthForAccessory;	// IMP=0x0000000100061818
- (void)_updateTitleHeightCache;	// IMP=0x00000001000616f8
- (id)_textColorForFocus:(_Bool)arg1;	// IMP=0x0000000100061634
- (void)_showPressState;	// IMP=0x0000000100061454
@property(readonly, nonatomic, getter=_imageViewCenter) struct CGPoint imageViewCenter;
- (void)_layoutSubviewsAnimated:(_Bool)arg1 focused:(_Bool)arg2 focusUpdateContext:(id)arg3 focusAnimationCoordinator:(id)arg4;	// IMP=0x000000010005fd4c
- (double)_maxTitleWidthWithFocus:(_Bool)arg1;	// IMP=0x000000010005fc20
- (id)_highlightFilterChain:(_Bool)arg1;	// IMP=0x000000010005fafc
- (void)_ensureTitle;	// IMP=0x000000010005fa60
- (void)_detachMotionEffects;	// IMP=0x000000010005fa48
- (void)_attachMotionEffects;	// IMP=0x000000010005f898
@property(readonly, nonatomic, getter=_imageConfiguration) _UIStackedImageConfiguration *imageConfiguration;
- (Class)_labelClass;	// IMP=0x000000010005f7e4
- (double)_scaleForImageViewState;	// IMP=0x000000010005f5bc
- (id)layeredImageContainerLayer;	// IMP=0x000000010005ecb4
@property(readonly, nonatomic, getter=_isPressStateAnimating) _Bool pressStateAnimating;
@property(readonly, nonatomic, getter=_isPressed) _Bool pressed;
- (void)clearPressStateWithDuration:(double)arg1;	// IMP=0x000000010005e93c
- (void)clearPressState;	// IMP=0x000000010005e92c
@property(readonly, nonatomic) _Bool allowsMotionEffects;
- (void)setOverlay:(id)arg1;	// IMP=0x000000010005e834
- (void)prepareForReuse;	// IMP=0x000000010005e77c
- (id)_preferredConfigurationForFocusAnimation:(long long)arg1 inContext:(id)arg2;	// IMP=0x000000010005e634
- (_Bool)_unapplyMotionEffect:(id)arg1;	// IMP=0x000000010005e62c
- (void)setHighlighted:(_Bool)arg1;	// IMP=0x000000010005e4b8
- (void)layoutSubviews;	// IMP=0x000000010005e448
- (_Bool)_applyKeyPathsAndRelativeValues:(id)arg1 forMotionEffect:(id)arg2;	// IMP=0x000000010005e36c
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010005e360
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010005e294
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010005e1c8
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010005e0fc
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x000000010005dfd8
- (void)willMoveToSuperview:(id)arg1;	// IMP=0x000000010005df68
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010005de30
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010005dbe8

// Remaining properties
@property(readonly, nonatomic) _Bool canBecomeFocused;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, copy, nonatomic) NSString *focusGroupIdentifier;
@property(readonly, nonatomic) id <UIFocusItemContainer> focusItemContainer;
@property(readonly, nonatomic) struct CGRect frame;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) __weak id <UIFocusEnvironment> parentFocusEnvironment;
@property(readonly, copy, nonatomic) NSArray *preferredFocusEnvironments;
@property(readonly, nonatomic) __weak UIView *preferredFocusedView;
@property(readonly) Class superclass;

@end

