//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "HBItemOrderProvisionedApplicationIdentifiersRule.h"

#import "HBItemOrderRule-Protocol.h"

@class NSString;

@interface HBItemOrderArcadeApplicationRule : HBItemOrderProvisionedApplicationIdentifiersRule <HBItemOrderRule>
{
}

- (id)insertApplications:(id)arg1 into:(id)arg2;	// IMP=0x00000001000473f4
- (_Bool)evaluateWithApplication:(id)arg1;	// IMP=0x0000000100047348
@property(readonly, nonatomic) unsigned long long processingLimit;
- (id)initWithProvisionedBundleIdentifiers:(id)arg1;	// IMP=0x000000010004730c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

