//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

@class UILabel;

@interface HBTopShelfSectionLabel : UICollectionReusableView
{
    UILabel *_textLabel;	// 8 = 0x8
}

+ (struct CGSize)sizeForString:(id)arg1;	// IMP=0x000000010003dbe8
- (void).cxx_destruct;	// IMP=0x000000010003e0a4
@property(readonly, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010003dfd0
- (void)_updateTextLabelAppearance;	// IMP=0x000000010003ddf4
- (void)applyLayoutAttributes:(id)arg1;	// IMP=0x000000010003d95c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010003d7b4

@end

