//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol HBUITopShelfContentViewControllerDelegate;

@protocol HBUITopShelfContentViewController <NSObject>
@property(readonly, nonatomic) unsigned long long contentStyle;
@property(nonatomic, getter=isContentOccluded) _Bool contentOccluded;
@property(nonatomic) __weak id <HBUITopShelfContentViewControllerDelegate> delegate;
@end

