//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSSet.h>

@interface NSSet (CloudServices)
- (_Bool)cs_containsObjectForCloudRecordIdentifier:(id)arg1;	// IMP=0x0000000100039af8
- (_Bool)cs_containsObjectForAppIdentifier:(id)arg1;	// IMP=0x0000000100039a48
@end

