//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TVServices/TVTopShelfSectionedItem.h>

@interface TVTopShelfSectionedItem (HBTopShelf)
+ (long long)_hb_genericPlaceholderForSectionedImageShape:(unsigned long long)arg1;	// IMP=0x00000001000635f0
- (_Bool)_hb_hasPodcastsRelatedMediaTypeWithApplicationIdentifier:(id)arg1;	// IMP=0x00000001000634b8
- (_Bool)_hb_hasMusicRelatedMediaTypeWithApplicationIdentifier:(id)arg1;	// IMP=0x0000000100063360
- (_Bool)_hb_hasPhotoRelatedMediaTypeWithApplicationIdentifier:(id)arg1;	// IMP=0x0000000100063344
- (_Bool)_hb_hasTVRelatedMediaTypeWithApplicationIdentifier:(id)arg1;	// IMP=0x0000000100063200
- (_Bool)_hb_hasMovieRelatedMediaTypeWithApplicationIdentifier:(id)arg1;	// IMP=0x0000000100063160
- (long long)hb_placeholderAssetTypeWithApplicationIdentifier:(id)arg1;	// IMP=0x0000000100063024
@property(readonly, nonatomic) struct CGSize hb_imageSize;
@property(readonly, nonatomic) unsigned long long hb_imageShape;
@end

