//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtCV7TVMusic8Backdrop17CompositeRenderer : NSObject
{
    MISSING_TYPE *visualizerIntensity;	// 8 = 0x8
    MISSING_TYPE *paused;	// 12 = 0xc
    MISSING_TYPE *crossfadeDuration;	// 16 = 0x10
    MISSING_TYPE *textureLoadingToken;	// 0 = 0x0
    MISSING_TYPE *context;	// 1869770847 = 0x6f72705f
    MISSING_TYPE *uniforms;	// 0 = 0x0
    MISSING_TYPE *imageScale;	// 1163157343 = 0x45545f5f
    MISSING_TYPE *spectrumAnalysis;	// 0 = 0x0
    MISSING_TYPE *aspectRatio;	// 0 = 0x0
    MISSING_TYPE *renderers;	// 0 = 0x0
}

- (void).cxx_destruct;	// IMP=0x00000001000de5e8
- (id)init;	// IMP=0x00000001000de6bc

@end

