//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtCV7TVMusic8Backdrop17CompositeRenderer.h"

#import "MTKViewDelegate-Protocol.h"

@interface _TtCV7TVMusic8Backdrop17CompositeRenderer (TVMusic) <MTKViewDelegate>
- (void)drawInMTKView:(id)arg1;	// IMP=0x00000001000deb48
- (void)mtkView:(id)arg1 drawableSizeWillChange:(struct CGSize)arg2;	// IMP=0x00000001000de7f4
@end

