//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC7TVMusic13TVMLShapeView : UIView
{
    MISSING_TYPE *cornerRadius;	// 8 = 0x8
    MISSING_TYPE *shapeContentType;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00000001000db59c
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x00000001000db568
- (void)layoutSubviews;	// IMP=0x00000001000db53c
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000db388
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000db368

@end

