//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MediaPlayer/MPSectionedCollection.h>

@interface MPSectionedCollection (TVMusic)
- (void)tvm_enumerateItemsUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000100027148
- (void)tvm_enumerateItemsInSectionAtIndex:(long long)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100027070
- (void)tvm_enumerateSectionsUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000100026fa0
@end

