//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIFocusContainerGuide;

@interface TVFocusRedirectView : UIView
{
    UIFocusContainerGuide *_containerGuide;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100030098
@property(readonly, nonatomic) UIFocusContainerGuide *containerGuide; // @synthesize containerGuide=_containerGuide;
- (void)layoutSubviews;	// IMP=0x000000010003001c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010002ff78

@end

