//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TVPMediaItem-Protocol.h"

@class MPModelObject, NSMutableDictionary, NSString, TVCKMutableBookmark, TVPBaseMediaItem;

@interface TVMusicMPObjectMediaItem : NSObject <TVPMediaItem>
{
    MPModelObject *_modelObject;	// 8 = 0x8
    NSMutableDictionary *_mediaItemMetadata;	// 16 = 0x10
    TVPBaseMediaItem *_dataItem;	// 24 = 0x18
    TVCKMutableBookmark *_bookmark;	// 32 = 0x20
}

+ (double)_playedThresholdTimeForDuration:(double)arg1;	// IMP=0x00000001000a03a0
- (void).cxx_destruct;	// IMP=0x00000001000a0478
@property(retain, nonatomic) TVCKMutableBookmark *bookmark; // @synthesize bookmark=_bookmark;
@property(retain, nonatomic) TVPBaseMediaItem *dataItem; // @synthesize dataItem=_dataItem;
@property(retain, nonatomic) NSMutableDictionary *mediaItemMetadata; // @synthesize mediaItemMetadata=_mediaItemMetadata;
@property(retain, nonatomic) MPModelObject *modelObject; // @synthesize modelObject=_modelObject;
- (void)updateBookmarkWithSuggestedTime:(double)arg1 forElapsedTime:(double)arg2 duration:(double)arg3 playbackOfMediaItemIsEnding:(_Bool)arg4;	// IMP=0x00000001000a01c8
- (void)performMediaItemMetadataTransactionWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001000a0110
- (void)removeMediaItemMetadataForProperty:(id)arg1;	// IMP=0x00000001000a00a4
- (void)setMediaItemMetadata:(id)arg1 forProperty:(id)arg2;	// IMP=0x000000010009ffc8
- (id)reportingDelegate;	// IMP=0x000000010009ffc0
- (_Bool)hasTrait:(id)arg1;	// IMP=0x000000010009fef0
- (_Bool)isEqualToMediaItem:(id)arg1;	// IMP=0x000000010009fe40
- (id)mediaItemURL;	// IMP=0x000000010009fe38
- (id)mediaItemMetadataForProperty:(id)arg1;	// IMP=0x000000010009f8f0
- (id)storeBrowseContentItemWithStorePlatformDictionary:(id)arg1;	// IMP=0x000000010009f714
- (_Bool)useBookmarks;	// IMP=0x000000010009f70c
- (id)initWithMPModelObject:(id)arg1;	// IMP=0x000000010009f6fc
- (id)initWithMPModelObject:(id)arg1 mediaItemMetadata:(id)arg2;	// IMP=0x000000010009f414

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

