//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TVMusicJSBag-Protocol.h"

@class AMSBag, NSArray, NSDictionary, NSString;

@interface TVMusicJSBag : NSObject <TVMusicJSBag>
{
    NSDictionary *_bagOptions;	// 8 = 0x8
    AMSBag *_amsBag;	// 16 = 0x10
    CDUnknownBlockType _amsBagRequestBlock;	// 24 = 0x18
    NSString *_profile;	// 32 = 0x20
    NSString *_profileVersion;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0000000100058010
@property(retain, nonatomic) NSString *profileVersion; // @synthesize profileVersion=_profileVersion;
@property(retain, nonatomic) NSString *profile; // @synthesize profile=_profile;
@property(copy, nonatomic) CDUnknownBlockType amsBagRequestBlock; // @synthesize amsBagRequestBlock=_amsBagRequestBlock;
- (unsigned long long)_AMSTypeFromString:(id)arg1;	// IMP=0x0000000100057ee4
- (void)_setDefaultAMSBagRequestBlock;	// IMP=0x0000000100057e70
@property(readonly, nonatomic) AMSBag *amsBag;
- (id)getArray:(id)arg1;	// IMP=0x0000000100057bbc
- (id)getValue:(id)arg1:(id)arg2;	// IMP=0x000000010005778c
- (_Bool)registerKeys:(id)arg1;	// IMP=0x00000001000574f8
@property(copy, nonatomic) NSDictionary *bagOptions;
@property(readonly, nonatomic) NSArray *supportedTypes;
- (id)init;	// IMP=0x0000000100057268

@end

