//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class TVMusicCloudProgressView, TVMusicLibraryManager, TVMusicLibraryTopMenuViewController, TVSStateMachine, UIActivityIndicatorView, UIView;

@interface TVMusicCloudViewController : UIViewController
{
    _Bool _viewVisible;	// 8 = 0x8
    TVSStateMachine *_stateMachine;	// 16 = 0x10
    TVMusicLibraryTopMenuViewController *_topMenuViewController;	// 24 = 0x18
    TVMusicCloudProgressView *_cloudProgressView;	// 32 = 0x20
    UIActivityIndicatorView *_activityIndicatorView;	// 40 = 0x28
    UIView *_noMusicView;	// 48 = 0x30
    UIView *_currentDisplayedView;	// 56 = 0x38
    TVMusicLibraryManager *_libraryManager;	// 64 = 0x40
}

+ (void)initialize;	// IMP=0x000000010000512c
- (void).cxx_destruct;	// IMP=0x0000000100007788
@property(nonatomic, getter=isViewVisible) _Bool viewVisible; // @synthesize viewVisible=_viewVisible;
@property(retain, nonatomic) TVMusicLibraryManager *libraryManager; // @synthesize libraryManager=_libraryManager;
@property(nonatomic) __weak UIView *currentDisplayedView; // @synthesize currentDisplayedView=_currentDisplayedView;
@property(retain, nonatomic) UIView *noMusicView; // @synthesize noMusicView=_noMusicView;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) TVMusicCloudProgressView *cloudProgressView; // @synthesize cloudProgressView=_cloudProgressView;
@property(retain, nonatomic) TVMusicLibraryTopMenuViewController *topMenuViewController; // @synthesize topMenuViewController=_topMenuViewController;
@property(retain, nonatomic) TVSStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
- (void)_libraryDidUpdate:(id)arg1;	// IMP=0x0000000100007598
- (void)_musicLibrarySyncProgress:(id)arg1;	// IMP=0x00000001000074c8
- (void)_musicLibraryStateChanged:(id)arg1;	// IMP=0x0000000100007470
- (void)_appDidBecomeActiveNotification:(id)arg1;	// IMP=0x0000000100007450
- (void)_handleLibraryState:(long long)arg1;	// IMP=0x00000001000072ec
- (void)_updateTopMenu;	// IMP=0x0000000100006f14
- (void)_registerStateMachineHandlers;	// IMP=0x0000000100006928
- (void)_removeCurrentView;	// IMP=0x00000001000068d4
- (void)_showSyncingView;	// IMP=0x0000000100006810
- (void)_removeWaitingView;	// IMP=0x0000000100006700
- (void)_showWaitingView;	// IMP=0x00000001000063e4
- (id)_menuItems;	// IMP=0x0000000100006264
- (void)_removeTopMenu;	// IMP=0x0000000100006128
- (void)_setScreenSaverEnabledForCloudLibrary;	// IMP=0x0000000100005f04
- (void)_removeNoMusicView;	// IMP=0x0000000100005df4
- (void)_showNoMusicView;	// IMP=0x0000000100005bec
- (void)_removeCloudProgressView;	// IMP=0x0000000100005adc
- (void)_showCloudProgressView;	// IMP=0x0000000100005918
- (id)preferredFocusEnvironments;	// IMP=0x0000000100005814
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x0000000100005740
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001000056ec
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010000552c
- (void)viewDidLoad;	// IMP=0x0000000100005334
- (void)dealloc;	// IMP=0x00000001000052bc
- (id)init;	// IMP=0x0000000100005160

@end

