//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TVCollectionViewDelegate-Protocol.h"
#import "UICollectionViewDataSourcePrefetching-Protocol.h"
#import "UICollectionViewDataSource_Private-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class MPModelLibraryRequest, MPModelResponse, MPSectionedCollection, NSIndexPath, NSString, TVCollectionView, TVMusicLibraryHeaderView;
@protocol MPLazySectionedCollectionDataSource;

@interface TVMusicLibrarySongsViewController : UIViewController <TVCollectionViewDelegate, UICollectionViewDataSource_Private, UIGestureRecognizerDelegate, UICollectionViewDataSourcePrefetching>
{
    _Bool _visibleOnScreen;	// 8 = 0x8
    _Bool _shouldUpdateOnViewDidAppear;	// 9 = 0x9
    TVCollectionView *_collectionView;	// 16 = 0x10
    TVMusicLibraryHeaderView *_headerView;	// 24 = 0x18
    MPModelLibraryRequest *_libraryRequest;	// 32 = 0x20
    MPModelResponse *_lastReceivedResponse;	// 40 = 0x28
    NSIndexPath *_focusToIndexPath;	// 48 = 0x30
    MPSectionedCollection *_songs;	// 56 = 0x38
    id <MPLazySectionedCollectionDataSource> _sectionedCollectionDataSource;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x000000010009c6d0
@property(retain, nonatomic) id <MPLazySectionedCollectionDataSource> sectionedCollectionDataSource; // @synthesize sectionedCollectionDataSource=_sectionedCollectionDataSource;
@property(retain, nonatomic) MPSectionedCollection *songs; // @synthesize songs=_songs;
@property(retain, nonatomic) NSIndexPath *focusToIndexPath; // @synthesize focusToIndexPath=_focusToIndexPath;
@property(retain, nonatomic) MPModelResponse *lastReceivedResponse; // @synthesize lastReceivedResponse=_lastReceivedResponse;
@property(retain, nonatomic) MPModelLibraryRequest *libraryRequest; // @synthesize libraryRequest=_libraryRequest;
@property(retain, nonatomic) TVMusicLibraryHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) TVCollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void)collectionView:(id)arg1 prefetchItemsAtIndexPaths:(id)arg2;	// IMP=0x000000010009c41c
- (void)_invalidateResultsWithResponse:(id)arg1;	// IMP=0x000000010009c31c
- (void)_modelResponseDidInvalidate:(id)arg1;	// IMP=0x000000010009c2cc
- (void)_playSongAtIndexPath:(id)arg1;	// IMP=0x000000010009c174
- (id)_placeholderImage;	// IMP=0x000000010009c110
- (void)_selectedSortButton;	// IMP=0x000000010009c060
- (void)_selectedShuffleButton;	// IMP=0x000000010009bff4
- (void)_selectedPlayButton;	// IMP=0x000000010009bf48
- (void)_processResponse:(id)arg1;	// IMP=0x000000010009bdd8
- (void)_processResponse:(id)arg1 error:(id)arg2;	// IMP=0x000000010009bd28
- (void)_performRequest;	// IMP=0x000000010009bb64
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x000000010009b868
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x000000010009b814
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x000000010009b7c8
- (id)collectionView:(id)arg1 indexPathForIndexTitle:(id)arg2 atIndex:(long long)arg3;	// IMP=0x000000010009b6d4
- (id)indexTitlesForCollectionView:(id)arg1;	// IMP=0x000000010009b680
- (void)collectionView:(id)arg1 didUpdateFocusInContext:(id)arg2 withAnimationCoordinator:(id)arg3;	// IMP=0x000000010009b250
- (id)indexPathForPreferredFocusedViewInCollectionView:(id)arg1;	// IMP=0x000000010009b240
- (void)collectionViewNeedsFocusUpdate:(id)arg1;	// IMP=0x000000010009b234
- (void)collectionView:(id)arg1 didReceiveLongPressForItemAtIndexPath:(id)arg2;	// IMP=0x000000010009b19c
- (_Bool)collectionView:(id)arg1 shouldHandleLongPressForItemAtIndexPath:(id)arg2;	// IMP=0x000000010009b194
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x000000010009b06c
- (void)scrollViewDidScroll:(id)arg1;	// IMP=0x000000010009af44
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x000000010009aeac
- (id)preferredFocusEnvironments;	// IMP=0x000000010009ae10
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x000000010009ac84
- (void)viewWillLayoutSubviews;	// IMP=0x000000010009ab00
- (void)_handlePlayPause:(id)arg1;	// IMP=0x000000010009a928
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010009a8b4
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x000000010009a868
- (void)viewDidLoad;	// IMP=0x000000010009a248
- (id)initWithLibraryRequest:(id)arg1;	// IMP=0x0000000100099efc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

