//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TVImageLoader-Protocol.h"

@class NSString;

@interface TVMusicMPArtworkCatalogLoader : NSObject <TVImageLoader>
{
}

+ (id)sharedInstance;	// IMP=0x00000001000a95b4
- (id)_identifierForMPModelObject:(id)arg1;	// IMP=0x00000001000aad94
- (void)cancelLoad:(id)arg1;	// IMP=0x00000001000aad90
- (void)_loadArtworkForMPObject:(id)arg1 scaleToSize:(struct CGSize)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001000aa8a0
- (id)loadImageForObject:(id)arg1 scaleToSize:(struct CGSize)arg2 cropToFit:(_Bool)arg3 imageDirection:(long long)arg4 requestLoader:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;	// IMP=0x00000001000a9788
- (id)imageKeyForObject:(id)arg1;	// IMP=0x00000001000a9620

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

