//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TVPMusicNowPlayingBackgroundProvider-Protocol.h"

@class MISSING_TYPE, UIImage;

@interface TVMusicNowPlayingArtworkVisualizerView : UIView <TVPMusicNowPlayingBackgroundProvider>
{
    MISSING_TYPE *image;	// 8 = 0x8
    MISSING_TYPE *visualizer;	// 16 = 0x10
}

+ (_Bool)isSupported;	// IMP=0x00000001000ebe44
- (void).cxx_destruct;	// IMP=0x00000001000ec3c8
- (void)layoutSubviews;	// IMP=0x00000001000ec2e0
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000ec244
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000ec224
- (void)endThrottle;	// IMP=0x00000001000ebe18
- (void)beginThrottle;	// IMP=0x00000001000ebe10
@property(nonatomic, readonly) UIView *view;
@property(nonatomic, retain) UIImage *image; // @synthesize image;
- (_Bool)isBlurDisabled;	// IMP=0x00000001000ebd24

// Remaining properties
@property(nonatomic, readonly) _Bool blurDisabled;

@end

