//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface TVMusicLibraryButtonFactory : NSObject
{
}

+ (id)allSeasonsButton;	// IMP=0x000000010002a818
+ (id)goToShowButton;	// IMP=0x000000010002a720
+ (id)wideGoToArtistButtonWithArtistName:(id)arg1;	// IMP=0x000000010002a518
+ (id)wideGoToArtistButton;	// IMP=0x000000010002a508
+ (id)wideShuffleButton;	// IMP=0x000000010002a410
+ (id)widePlayButton;	// IMP=0x000000010002a318
+ (id)normalMoreButton;	// IMP=0x000000010002a220

@end

