//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "BKHIDEventClientDelegate-Protocol.h"
#import "BKHIDEventProcessor-Protocol.h"
#import "BKOrientationManagerObserver-Protocol.h"

@class BKAccelerometerClient, BKOrientationManager, BKSLocalDefaults, NSLock, NSMutableSet, NSString, SLGNotificationActivatedLogger;

@interface BKAccelerometerInterface : NSObject <BKHIDEventClientDelegate, BKOrientationManagerObserver, BKHIDEventProcessor>
{
    NSLock *_lock;	// 8 = 0x8
    NSMutableSet *_lock_accelerometerClients;	// 16 = 0x10
    NSMutableSet *_lock_cachedClients;	// 24 = 0x18
    BKAccelerometerClient *_lock_systemAppOrientationClient;	// 32 = 0x20
    BKOrientationManager *_lock_orientationManager;	// 40 = 0x28
    double _lock_samplingInterval;	// 48 = 0x30
    SLGNotificationActivatedLogger *_studyLog;	// 56 = 0x38
    BKSLocalDefaults *_localDefaults;	// 64 = 0x40
}

+ (id)sharedInstance;	// IMP=0x0000000100038e18
- (void).cxx_destruct;	// IMP=0x0000000100038a40
- (void)orientationManager:(id)arg1 deviceOrientationMayHaveChanged:(long long)arg2 changeSource:(long long)arg3 isDeviceOrientationLocked:(_Bool)arg4;	// IMP=0x00000001000388f4
- (void)_lock_systemAppSetOrientationEventsClient:(id)arg1 wantsOrientationEvents:(_Bool)arg2 auditToken:(const CDStruct_6ad76789 *)arg3;	// IMP=0x0000000100038610
- (void)_lock_clearSystemAppOrientationClient;	// IMP=0x00000001000385c8
- (id)_lock_existingClientForPort:(unsigned int)arg1;	// IMP=0x00000001000384f0
- (void)_updateSettings;	// IMP=0x00000001000381d4
- (void)_handleAccelerometerRequestForPort:(id)arg1 auditToken:(const CDStruct_6ad76789 *)arg2 updateBlock:(CDUnknownBlockType)arg3;	// IMP=0x0000000100038070
- (void)clientDied:(id)arg1;	// IMP=0x0000000100037fb0
- (long long)processEvent:(inout struct __IOHIDEvent **)arg1 sender:(id)arg2 dispatcher:(id)arg3;	// IMP=0x0000000100037cc4
@property(readonly, copy) NSString *description;
- (void)systemAppSetOrientationEventsClient:(id)arg1 wantsOrientationEvents:(_Bool)arg2 auditToken:(const CDStruct_6ad76789 *)arg3;	// IMP=0x0000000100037a94
- (void)bksAccelerometerClientRequestedOrientationEvents:(id)arg1 enabled:(_Bool)arg2 passiveEvents:(_Bool)arg3 auditToken:(const CDStruct_6ad76789 *)arg4;	// IMP=0x0000000100037a34
- (void)bksAccelerometerClientRequestedAccelerometerEvents:(id)arg1 updateInterval:(double)arg2 xThreshold:(float)arg3 yThreshold:(float)arg4 zThreshold:(float)arg5 auditToken:(const CDStruct_6ad76789 *)arg6;	// IMP=0x00000001000379d4
- (void)dealloc;	// IMP=0x0000000100037938
- (id)init;	// IMP=0x0000000100037730

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

