//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BKDisplayRenderOverlayPersistenceCoordinator : NSObject
{
    NSString *_rootPersistencePath;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x0000000100057444
- (void).cxx_destruct;	// IMP=0x0000000100057438
- (id)_fileNameForOverlay:(id)arg1;	// IMP=0x0000000100057348
- (id)_filePathForOverlay:(id)arg1;	// IMP=0x00000001000572b4
- (_Bool)destroyOverlay:(id)arg1;	// IMP=0x0000000100057224
- (_Bool)saveOverlay:(id)arg1;	// IMP=0x0000000100056bf4
- (id)rebuildPersistentOverlays;	// IMP=0x0000000100056820
- (id)init;	// IMP=0x0000000100056774

@end

