//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface BKMigrator : NSObject
{
}

- (_Bool)_moveRestoredFileAtPath:(id)arg1;	// IMP=0x0000000100050c74
- (void)_removeUnusedFiles;	// IMP=0x0000000100050a60
- (void)_migrateBackBoard;	// IMP=0x0000000100050a0c
- (void)migrateIfNecessary;	// IMP=0x0000000100050920

@end

