//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ManagedConfiguration/MCProfileConnection.h>

@class NSString;

@interface MCProfileConnection (PineBoardAdditions)
@property(readonly, nonatomic) _Bool pb_appRestrictionsProfileInstalled;
@property(readonly, copy, nonatomic) NSString *pb_diagnosticsUploadURLString;
@property(readonly, nonatomic) _Bool pb_usesManagedDiagnostics;
@end

