//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class PBApplicationSceneView, PBSnapshotLoadRequest;

@protocol PBApplicationSceneViewDelegate <NSObject>
- (void)applicationSceneView:(PBApplicationSceneView *)arg1 didUpdateReadiness:(_Bool)arg2;
- (void)applicationSceneViewDidUpdatePresentationMode:(PBApplicationSceneView *)arg1;
- (void)applicationSceneView:(PBApplicationSceneView *)arg1 willLoadSnapshotWithRequest:(PBSnapshotLoadRequest *)arg2;
@end

