//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface PBAttentionMonitorStateMachine : NSObject
{
    long long _state;	// 8 = 0x8
    _Bool _automaticEnabled;	// 16 = 0x10
    _Bool _enteredOnStateAutomatically;	// 17 = 0x11
    double _enabledOffset;	// 24 = 0x18
}

@property(nonatomic) double enabledOffset; // @synthesize enabledOffset=_enabledOffset;
- (void)_enterOffStateForced;	// IMP=0x000000010000ccc4
- (void)_enterOnStateForced;	// IMP=0x000000010000ccac
- (void)_enterOffStateAutomatically;	// IMP=0x000000010000cc94
- (void)_enterOnStateAutomatically;	// IMP=0x000000010000cc7c
- (_Bool)_canBeInOnStateAutomatically;	// IMP=0x000000010000cc5c
- (id)_logString;	// IMP=0x000000010000cbac
@property(readonly, nonatomic) _Bool enteredOnStateAutomatically;
- (void)enterOffStateForced;	// IMP=0x000000010000ca38
- (void)enterOnStateForced;	// IMP=0x000000010000c8ec
- (void)enterOffStateAutomatically;	// IMP=0x000000010000c79c
- (_Bool)adjustStateAutomatically;	// IMP=0x000000010000c48c
- (void)automaticDisable;	// IMP=0x000000010000c37c
- (void)automaticEnable;	// IMP=0x000000010000c270
@property(readonly, nonatomic, getter=isAutomaticEnabled) _Bool automaticEnabled;
- (void)_setStateOff;	// IMP=0x000000010000c140
- (void)_setStateOn;	// IMP=0x000000010000c034
@property(readonly, nonatomic) _Bool isOn;
@property(readonly, nonatomic) _Bool isOff;
- (id)init;	// IMP=0x000000010000bf04

@end

