//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSString;

@interface PBClearApplicationDataContainerCacheOperation : NSOperation
{
    NSString *_applicationIdentifier;	// 8 = 0x8
    CDUnknownBlockType _clearApplicationDataContainerCacheCompletionHandler;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100087260
@property(copy, nonatomic) CDUnknownBlockType clearApplicationDataContainerCacheCompletionHandler; // @synthesize clearApplicationDataContainerCacheCompletionHandler=_clearApplicationDataContainerCacheCompletionHandler;
@property(readonly, nonatomic) NSString *applicationIdentifier; // @synthesize applicationIdentifier=_applicationIdentifier;
- (void)main;	// IMP=0x0000000100086cd8
- (id)initWithApplicationIdentifier:(id)arg1;	// IMP=0x0000000100086bcc

@end

