//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <BaseBoard/BSTransaction.h>

@class BSWatchdog;

@interface PBKioskAppAnimationTransaction : BSTransaction
{
    BSTransaction *_animateTransaction;	// 8 = 0x8
    BSWatchdog *_watchdog;	// 16 = 0x10
    CDStruct_ce5a068a _context;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0000000100217e34
@property(readonly, nonatomic) BSWatchdog *watchdog; // @synthesize watchdog=_watchdog;
@property(readonly, nonatomic) BSTransaction *animateTransaction; // @synthesize animateTransaction=_animateTransaction;
@property(readonly, nonatomic) CDStruct_ce5a068a context; // @synthesize context=_context;
- (void)_prepareAnimationInTransaction:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100216f4c
- (void)_didComplete;	// IMP=0x0000000100216dd8
- (void)_willAddChildTransaction:(id)arg1;	// IMP=0x0000000100216ce4
- (void)_begin;	// IMP=0x00000001002168d0
- (_Bool)_canBeInterrupted;	// IMP=0x00000001002168b0
- (id)initWithSceneLayoutViewController:(id)arg1 fromViewController:(id)arg2 toViewController:(id)arg3 shouldPlaySound:(_Bool)arg4 isLaunchingFromKiosk:(_Bool)arg5;	// IMP=0x00000001002166d8

@end

