//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class PBSceneHandle, UIActivityIndicatorView, UIImageView, UILabel, UIStackView, UIViewPropertyAnimator, UIVisualEffectView;

@interface PBUserSwitchingShroudView : UIView
{
    _Bool _animating;	// 8 = 0x8
    _Bool _overLiveScene;	// 9 = 0x9
    PBSceneHandle *_sceneHandle;	// 16 = 0x10
    UIView *_applicationSnapshotView;	// 24 = 0x18
    UIVisualEffectView *_backgroundVisualEffectView;	// 32 = 0x20
    UIStackView *_stackView;	// 40 = 0x28
    UIImageView *_appIconImageView;	// 48 = 0x30
    UILabel *_switchingLabel;	// 56 = 0x38
    UIActivityIndicatorView *_activityIndicatorView;	// 64 = 0x40
    UIViewPropertyAnimator *_backgroundFadeAnimator;	// 72 = 0x48
    UIViewPropertyAnimator *_appIconFadeAnimator;	// 80 = 0x50
    UIViewPropertyAnimator *_appIconScaleAnimator;	// 88 = 0x58
    UIViewPropertyAnimator *_labelAndActivityIndicatorFadeAnimator;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x00000001000e65c0
@property(retain, nonatomic) UIViewPropertyAnimator *labelAndActivityIndicatorFadeAnimator; // @synthesize labelAndActivityIndicatorFadeAnimator=_labelAndActivityIndicatorFadeAnimator;
@property(retain, nonatomic) UIViewPropertyAnimator *appIconScaleAnimator; // @synthesize appIconScaleAnimator=_appIconScaleAnimator;
@property(retain, nonatomic) UIViewPropertyAnimator *appIconFadeAnimator; // @synthesize appIconFadeAnimator=_appIconFadeAnimator;
@property(retain, nonatomic) UIViewPropertyAnimator *backgroundFadeAnimator; // @synthesize backgroundFadeAnimator=_backgroundFadeAnimator;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) UILabel *switchingLabel; // @synthesize switchingLabel=_switchingLabel;
@property(retain, nonatomic) UIImageView *appIconImageView; // @synthesize appIconImageView=_appIconImageView;
@property(retain, nonatomic) UIStackView *stackView; // @synthesize stackView=_stackView;
@property(retain, nonatomic) UIVisualEffectView *backgroundVisualEffectView; // @synthesize backgroundVisualEffectView=_backgroundVisualEffectView;
@property(readonly, nonatomic) UIView *applicationSnapshotView; // @synthesize applicationSnapshotView=_applicationSnapshotView;
@property(readonly, nonatomic, getter=isOverLiveScene) _Bool overLiveScene; // @synthesize overLiveScene=_overLiveScene;
@property(nonatomic, getter=isAnimating) _Bool animating; // @synthesize animating=_animating;
@property(readonly, nonatomic) PBSceneHandle *sceneHandle; // @synthesize sceneHandle=_sceneHandle;
- (void)_addSceneSnapshot;	// IMP=0x00000001000e5f6c
- (void)_setBackgroundPresented:(_Bool)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000e5a60
- (void)_setLabelAndActivityIndicatorPresented:(_Bool)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000e539c
- (void)_dismissAppIconImageViewAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e4c10
- (void)_presentAppIconImageViewAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e444c
- (void)_setContinuousCornerRadius:(double)arg1;	// IMP=0x00000001000e4284
- (void)dismissAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e3df8
- (void)presentAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e3958
- (id)initWithSceneHandle:(id)arg1 isOverLiveScene:(_Bool)arg2;	// IMP=0x00000001000e2190

@end

