//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PBAttentionMonitorStateMachine.h"

#import "PBScreenSaverManagerObserver-Protocol.h"

@class NSString;

@interface ScreenSaverSM : PBAttentionMonitorStateMachine <PBScreenSaverManagerObserver>
{
}

- (void)screenSaverManagerDidDismissScreenSaver:(id)arg1;	// IMP=0x0000000100011b88
- (void)screenSaverManagerDidPresentScreenSaver:(id)arg1;	// IMP=0x0000000100011b1c
- (void)screenSaverManagerWillPresentScreenSaver:(id)arg1;	// IMP=0x0000000100011ab8
- (void)_enterOffStateForced;	// IMP=0x0000000100011aa4
- (void)_enterOnStateForced;	// IMP=0x0000000100011a30
- (void)_enterOffStateAutomatically;	// IMP=0x00000001000119cc
- (void)_enterOnStateAutomatically;	// IMP=0x000000010001179c
- (_Bool)_canBeInOnStateAutomatically;	// IMP=0x0000000100010fc8
- (id)init;	// IMP=0x00000001000109a0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

