/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 27, 2020 at 12:50:23 AM Mountain Standard Time
* Operating System: Version 14.0 (Build 18J386)
* Image Source: /usr/lib/libMemoryResourceException.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray;

@interface FPImageEnumerator : NSObject {

	NSArray* _images;
	unsigned long long _index;

}
-(id)initWithImages:(id)arg1 ;
-(id)nextImageForStart:(unsigned long long)arg1 end:(unsigned long long)arg2 ;
@end

