//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC6Arcade20OfferAlertController : _TtCs12_SwiftObject
{
    MISSING_TYPE *flowController;	// 16 = 0x10
    MISSING_TYPE *actionRunner;	// 56 = 0x38
    MISSING_TYPE *action;	// 64 = 0x40
    MISSING_TYPE *actionSender;	// 72 = 0x48
}

@end

