//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC6Arcade22BaseCollectionViewCell.h"

@interface _TtC6Arcade22CardCollectionViewCell : _TtC6Arcade22BaseCollectionViewCell
{
}

- (void).cxx_destruct;	// IMP=0x00000001000400b0
- (id)_preferredConfigurationForFocusAnimation:(long long)arg1 inContext:(id)arg2;	// IMP=0x000000010003ff94
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010003fec8

@end

