//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC6Arcade31LargeBreakoutCollectionViewCell.h"

@interface _TtC6Arcade32UpsellBreakoutCollectionViewCell : _TtC6Arcade31LargeBreakoutCollectionViewCell
{
}

- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100044650

@end

