//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCC6Arcade28HorizontalShelfContainerCellP33_1E6BB4DDCDAD15F8D7B4EECC014D169010DataSource : _TtCs12_SwiftObject
{
    MISSING_TYPE *cellType;	// 16 = 0x10
    MISSING_TYPE *artworkLoader;	// 24 = 0x18
    MISSING_TYPE *objectGraph;	// 32 = 0x20
    MISSING_TYPE *containerDelegate;	// 40 = 0x28
    MISSING_TYPE *presentationHints;	// 56 = 0x38
    MISSING_TYPE *pageTraits;	// 64 = 0x40
    MISSING_TYPE *seeAllAction;	// 72 = 0x48
    MISSING_TYPE *layout;	// 80 = 0x50
}

@end

