//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC6Arcade22BaseCollectionViewCell.h"

@class MISSING_TYPE;

@interface _TtC6Arcade32SmallStoryCardCollectionViewCell : _TtC6Arcade22BaseCollectionViewCell
{
    MISSING_TYPE *mediaView;	// 176 = 0xb0
    MISSING_TYPE *detailsView;	// 184 = 0xb8
}

- (void).cxx_destruct;	// IMP=0x0000000100114c88
- (void)prepareForReuse;	// IMP=0x00000001001149cc
- (void)layoutSubviews;	// IMP=0x0000000100114898
@property(nonatomic) struct CATransform3D transform3D;
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100114238

@end

