//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtCC6Arcade28AnnotationCollectionViewCell8ItemView : UIView
{
    MISSING_TYPE *headingTextLabel;	// 8 = 0x8
    MISSING_TYPE *textLabel;	// 16 = 0x10
    MISSING_TYPE *subTextLabel;	// 24 = 0x18
    MISSING_TYPE *listTextLabel;	// 32 = 0x20
    MISSING_TYPE *isLastItem;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0000000100061ebc
- (struct JUMeasurements)measurementsWithFitting:(struct CGSize)arg1 in:(id)arg2;	// IMP=0x0000000100061694
- (void)layoutSubviews;	// IMP=0x00000001000614a8
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000611fc
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000611dc

@end

