//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC6Arcade31ProductBackgroundUberEffectView : UIView
{
    MISSING_TYPE *layer1;	// 8 = 0x8
    MISSING_TYPE *layer2;	// 16 = 0x10
    MISSING_TYPE *layer3;	// 24 = 0x18
    MISSING_TYPE *maskingView;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x000000010010e224
- (void)layoutSubviews;	// IMP=0x000000010010e1c4
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010010dfa4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010010df84

@end

