//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC6Arcade22BaseCollectionViewCell.h"

@class MISSING_TYPE;

@interface _TtC6Arcade29FramedMediaCollectionViewCell : _TtC6Arcade22BaseCollectionViewCell
{
    MISSING_TYPE *captionView;	// 176 = 0xb0
    MISSING_TYPE *hasRoundedCorners;	// 184 = 0xb8
    MISSING_TYPE *hasCaption;	// 185 = 0xb9
    MISSING_TYPE *preferredArtworkSize;	// 192 = 0xc0
}

- (void).cxx_destruct;	// IMP=0x000000010003c818
- (void)layoutSubviews;	// IMP=0x000000010003c7a4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x000000010003c3d4

@end

