//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray;

@interface _TtC6ArcadeP33_00599866A72A07D21D537A40244FFFF312PanFocusView : UIView
{
}

- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000b1624
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000b15b8
@property(nonatomic, readonly) NSArray *preferredFocusEnvironments;
@property(nonatomic, readonly) _Bool canBecomeFocused;

@end

