//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "UITabBarControllerDelegate-Protocol.h"

@class MISSING_TYPE;

@interface _TtC6Arcade17TabChangeDelegate : NSObject <UITabBarControllerDelegate>
{
    MISSING_TYPE *metricsPipeline;	// 0 = 0x0
}

- (void).cxx_destruct;	// IMP=0x000000010014c710
- (id)init;	// IMP=0x000000010014c798
- (void)tabBarController:(id)arg1 didSelectViewController:(id)arg2;	// IMP=0x000000010014c678
- (_Bool)tabBarController:(id)arg1 shouldSelectViewController:(id)arg2;	// IMP=0x000000010014c5f8

@end

