//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC6Arcade22BaseCollectionViewCell.h"

@class MISSING_TYPE, _TtC6Arcade15LockupMediaView, _TtC6Arcade15SmallLockupView, _TtC6Arcade16DynamicTypeLabel, _TtC6Arcade9VideoView;

@interface _TtC6Arcade34MixedMediaLockupCollectionViewCell : _TtC6Arcade22BaseCollectionViewCell
{
    MISSING_TYPE *backdropView;	// 176 = 0xb0
    MISSING_TYPE *lockupView;	// 184 = 0xb8
    MISSING_TYPE *mediaView;	// 192 = 0xc0
    MISSING_TYPE *taglineLabel;	// 200 = 0xc8
    MISSING_TYPE *overrideLockupPosition;	// 208 = 0xd0
    MISSING_TYPE *alwaysIncludeTaglineSpace;	// 209 = 0xd1
    MISSING_TYPE *pillView;	// 216 = 0xd8
}

- (void).cxx_destruct;	// IMP=0x00000001000a7bec
@property(nonatomic, readonly) _TtC6Arcade15LockupMediaView *accessibilityMediaView;
@property(nonatomic, readonly) _TtC6Arcade9VideoView *accessibilityVideoView;
@property(nonatomic, readonly) _TtC6Arcade16DynamicTypeLabel *accessibilityTaglineLabel;
@property(nonatomic, readonly) _TtC6Arcade15SmallLockupView *accessibilityLockupView;
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000001000a7a30
@property(nonatomic, readonly) struct CGRect jet_focusedFrame;
- (void)prepareForReuse;	// IMP=0x00000001000a767c
- (void)layoutSubviews;	// IMP=0x00000001000a7590
@property(nonatomic) struct CATransform3D transform3D;
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000a6fa8

@end

