//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <OnBoardingKit/OBPrivacyLinkController.h>

@interface OBPrivacyLinkController (AS_PresentationAdditions)
+ (void)load;	// IMP=0x00000001000051a4
- (void)as_linkPressed;	// IMP=0x00000001000051e4
@end

