//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DIBaseXPCHandler.h"

@class NSXPCListenerEndpoint;

@interface DIClient2IODaemonXPCHandler : DIBaseXPCHandler
{
    NSXPCListenerEndpoint *_xpcListenerEndpoint;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100030324
@property(retain, nonatomic) NSXPCListenerEndpoint *xpcListenerEndpoint; // @synthesize xpcListenerEndpoint=_xpcListenerEndpoint;
- (_Bool)addToRefCountWithError:(id *)arg1;	// IMP=0x0000000100030198
- (id)remoteObjectInterface;	// IMP=0x000000010003017c
- (void)createConnection;	// IMP=0x000000010002fd7c
- (id)initWithEndpoint:(id)arg1;	// IMP=0x000000010002fcfc

@end

