//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DIBaseParams.h"

@class FileLocalXPC, NSURL;

@interface DIConvertParams : DIBaseParams
{
    _Bool _inPlaceConversion;	// 8 = 0x8
    long long _outputFormat;	// 16 = 0x10
    unsigned long long _maxRawUDIFRunSize;	// 24 = 0x18
    NSURL *_outputURL;	// 32 = 0x20
    FileLocalXPC *_outputBackendXPC;	// 40 = 0x28
}

+ (_Bool)supportsSecureCoding;	// IMP=0x000000010000b8ec
- (void).cxx_destruct;	// IMP=0x000000010001c9cc
@property(retain, nonatomic) FileLocalXPC *outputBackendXPC; // @synthesize outputBackendXPC=_outputBackendXPC;
@property(retain, nonatomic) NSURL *outputURL; // @synthesize outputURL=_outputURL;
@property(nonatomic) unsigned long long maxRawUDIFRunSize; // @synthesize maxRawUDIFRunSize=_maxRawUDIFRunSize;
@property(nonatomic) long long outputFormat; // @synthesize outputFormat=_outputFormat;
@property(readonly, nonatomic) _Bool inPlaceConversion; // @synthesize inPlaceConversion=_inPlaceConversion;
- (void)invalidate;	// IMP=0x000000010001c8e0
- (_Bool)convertWithError:(id *)arg1;	// IMP=0x000000010001be40
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000010001bcb0
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010001bb08
- (id)initForInplaceWithURL:(id)arg1 error:(id *)arg2;	// IMP=0x000000010001bad0
- (id)initWithInputURL:(id)arg1 outputURL:(id)arg2 error:(id *)arg3;	// IMP=0x000000010001b91c
- (id)initWithURL:(id)arg1 fileOpenMode:(unsigned short)arg2 error:(id *)arg3;	// IMP=0x000000010001b7a8

@end

