//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SATVAirplay2DataSource-Protocol.h"

@class NSArray, NSString;
@protocol SATVAirplay2DataSourceObject;

@interface SATVAirplay2TapToSetupDataSource : NSObject <SATVAirplay2DataSource>
{
    NSArray *_homes;	// 8 = 0x8
    id <SATVAirplay2DataSourceObject> _preferredHome;	// 16 = 0x10
}

+ (id)new;	// IMP=0x0000000100052e4c
- (void).cxx_destruct;	// IMP=0x00000001000534b4
@property(readonly, copy, nonatomic) id <SATVAirplay2DataSourceObject> preferredHome; // @synthesize preferredHome=_preferredHome;
@property(readonly, copy, nonatomic) NSArray *homes; // @synthesize homes=_homes;
@property(readonly, copy) NSString *description;
- (void)removeObserver:(id)arg1;	// IMP=0x00000001000533b8
- (void)addObserver:(id)arg1;	// IMP=0x00000001000533b4
- (id)roomWithName:(id)arg1 inHome:(id)arg2;	// IMP=0x0000000100053208
- (id)roomsForHome:(id)arg1;	// IMP=0x00000001000530b4
@property(readonly, nonatomic, getter=isReady) _Bool ready;
- (id)initWithHomeKitInfo:(id)arg1;	// IMP=0x0000000100052ea8
- (id)init;	// IMP=0x0000000100052e70

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

