//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "TVSKStep-Protocol.h"

@class NSString, SATVAirplay2ViewController;
@protocol TVSKStepDelegate;

@interface SATVAirplay2Step : NSObject <TVSKStep>
{
    id <TVSKStepDelegate> stepDelegate;	// 8 = 0x8
    SATVAirplay2ViewController *_airplay2ViewController;	// 16 = 0x10
}

+ (_Bool)_isSupportedForUpgradeWithContext:(id)arg1;	// IMP=0x00000001000047c4
+ (_Bool)_isSupportedWithSetupSession:(id)arg1;	// IMP=0x0000000100004770
+ (id)stableIdentifier;	// IMP=0x0000000100004228
- (void).cxx_destruct;	// IMP=0x0000000100004bd8
@property(retain, nonatomic) SATVAirplay2ViewController *airplay2ViewController; // @synthesize airplay2ViewController=_airplay2ViewController;
@property(nonatomic) __weak id <TVSKStepDelegate> stepDelegate; // @synthesize stepDelegate;
- (void)_completeStep;	// IMP=0x0000000100004b20
- (void)_showAirplay2ViewControllerWithHomeKitInfo:(id)arg1 isUpdateFlow:(_Bool)arg2;	// IMP=0x00000001000048f0
- (void)autoAdvance;	// IMP=0x00000001000046f0
- (id)executeStepForContext:(id)arg1;	// IMP=0x0000000100004234

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

