//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class TVSKLabel, UIStackView;
@protocol SATVExpressTapToSetupViewDataSource, SATVExpressTapToSetupViewDelegate;

@interface SATVExpressTapToSetupView : UIView
{
    id <SATVExpressTapToSetupViewDataSource> _dataSource;	// 8 = 0x8
    id <SATVExpressTapToSetupViewDelegate> _delegate;	// 16 = 0x10
    TVSKLabel *_titleLabel;	// 24 = 0x18
    TVSKLabel *_subtitleLabel;	// 32 = 0x20
    UIStackView *_cardsStackView;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0000000100046ab8
@property(readonly, nonatomic) UIStackView *cardsStackView; // @synthesize cardsStackView=_cardsStackView;
@property(readonly, nonatomic) TVSKLabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(readonly, nonatomic) TVSKLabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <SATVExpressTapToSetupViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <SATVExpressTapToSetupViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void)_populateCardsStackView;	// IMP=0x00000001000465e4
- (void)_handleLearnMoreButton;	// IMP=0x000000010004659c
- (void)_handleCustomizeSetupButton;	// IMP=0x0000000100046554
- (void)_handlePerformExpressSetupButton;	// IMP=0x000000010004650c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000458d8

@end

