//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MorphunAssetsClient : NSObject
{
}

+ (id)purgeResultToString:(long long)arg1;	// IMP=0x0000000100008ce8
+ (id)downloadResultToString:(long long)arg1;	// IMP=0x0000000100008b10
+ (id)queryResultToString:(long long)arg1;	// IMP=0x0000000100008a58
+ (id)platformSpecificLanguages;	// IMP=0x0000000100008a00
+ (id)removeLanguageSuffix:(id)arg1;	// IMP=0x00000001000089e8
+ (id)addLanguageSuffix:(id)arg1;	// IMP=0x00000001000089d0
+ (id)purgeAsset:(id)arg1;	// IMP=0x00000001000084b0
+ (_Bool)isUpdateNeededForLanguage:(id)arg1 neededAsset:(id *)arg2 uneededAssets:(id *)arg3 error:(id *)arg4;	// IMP=0x0000000100007e14
+ (_Bool)purgeAssetsForLanguage:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100007b28
+ (_Bool)updateAssetForLanguage:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100006bec
+ (_Bool)updateCatalogue:(id *)arg1;	// IMP=0x0000000100006534
+ (id)getAllLanguagePaths:(id *)arg1;	// IMP=0x0000000100006090
+ (id)removeAssetsForLanguages:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100005ba0
+ (id)updateAssetsForLanguages:(id)arg1 error:(id *)arg2;	// IMP=0x000000010000565c
+ (id)getAllAssetVersions;	// IMP=0x00000001000053a0
+ (id)getBuildAttributeIfSet:(id)arg1;	// IMP=0x00000001000052c4

@end

