//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDTaskOperation.h"

@interface DMDFetchUsersOperation : DMDTaskOperation
{
}

+ (id)requiredEntitlements;	// IMP=0x000000010004bdd8
+ (id)whitelistedClassesForRequest;	// IMP=0x000000010004bd9c

@end

