//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDTaskOperation.h"

@interface DMDFetchDeclarationCapabilitiesOperation : DMDTaskOperation
{
}

+ (_Bool)validateRequest:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100049a04
+ (id)requiredEntitlements;	// IMP=0x00000001000499f8
+ (id)whitelistedClassesForRequest;	// IMP=0x00000001000499bc
- (void)runWithRequest:(id)arg1;	// IMP=0x0000000100049a40
- (unsigned long long)queueGroup;	// IMP=0x0000000100049a38

@end

