//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "DMDTaskOperation.h"

@interface DMDStopManagingBooksOperation : DMDTaskOperation
{
}

+ (id)requiredEntitlements;	// IMP=0x0000000100065100
+ (id)whitelistedClassesForRequest;	// IMP=0x00000001000650c4

@end

