//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSXPCListenerDelegate-Protocol.h"
#import "SWCDownloaderDelegate-Protocol.h"
#import "SWCXPCServer-Protocol.h"

@class NSString, NSXPCListener, SWCDatabase, SWCDownloadScheduler, SWCDownloader;

@interface SWCManager : NSObject <NSXPCListenerDelegate, SWCDownloaderDelegate, SWCXPCServer>
{
    NSXPCListener *_xpcListener;	// 8 = 0x8
    struct optional<bool> _developerModeEnabled;	// 16 = 0x10
    SWCDatabase *_database;	// 24 = 0x18
    SWCDownloader *_downloader;	// 32 = 0x20
    SWCDownloadScheduler *_downloadScheduler;	// 40 = 0x28
}

+ (id)beginListening;	// IMP=0x00000001000177f8
+ (id)new;	// IMP=0x00000001000177bc
- (id).cxx_construct;	// IMP=0x000000010001da88
- (void).cxx_destruct;	// IMP=0x000000010001da40
@property(readonly) SWCDownloadScheduler *downloadScheduler; // @synthesize downloadScheduler=_downloadScheduler;
@property(readonly) SWCDownloader *downloader; // @synthesize downloader=_downloader;
@property(readonly) SWCDatabase *database; // @synthesize database=_database;
- (void)setDeveloperModeEnabled:(_Bool)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010001d5a8
- (void)getDeveloperModeEnabledWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010001d4f8
- (void)getTrackingDomains:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010001d2a0
- (void)removeSettingsForKeys:(id)arg1 serviceSpecifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010001cf28
- (void)removeSettingsForKeys:(id)arg1 serviceType:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010001cbe8
- (void)commitServiceSettings:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010001c6c8
- (void)getServiceSettingsWithServiceSpecifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010001c3d8
- (void)resetWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010001c160
- (void)showWithVerbosity:(unsigned char)arg1 isTTY:(_Bool)arg2 fileDescriptor:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010001ad44
- (void)addAllAppsWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010001aab8
- (void)setUserApprovalState:(unsigned char)arg1 forServiceWithServiceSpecifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x000000010001a62c
- (void)setDetails:(id)arg1 forServiceWithServiceSpecifier:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100019fd0
- (void)removeServiceWithServiceSpecifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000199e4
- (void)addServiceWithServiceSpecifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000193d4
- (void)getDetailsWithServiceSpecifier:(id)arg1 URL:(id)arg2 limit:(unsigned long long)arg3 callerAuditToken:(id)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x0000000100019020
- (void)waitForSiteApprovalWithServiceSpecifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100018e40
- (void)downloader:(id)arg1 failedToDownloadAASAFileFromDomain:(id)arg2 error:(id)arg3;	// IMP=0x0000000100018ae4
- (void)downloader:(id)arg1 didDownloadAASAFileContainingJSONObject:(id)arg2 fromDomain:(id)arg3 downloadRoute:(unsigned char)arg4;	// IMP=0x00000001000188e0
- (void)downloader:(id)arg1 willDownloadAASAFileFromDomain:(id)arg2;	// IMP=0x0000000100018788
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x0000000100018200
- (void)updateEntriesForAllBundlesIgnoringCurrentState:(_Bool)arg1;	// IMP=0x0000000100017a94
- (void)receiveSIGTERMSignal;	// IMP=0x0000000100017a5c
- (id)init;	// IMP=0x00000001000177c8
- (id)initWithDatabase:(id)arg1;	// IMP=0x00000001000176b4
- (_Bool)_isDeveloperModeEnabled;	// IMP=0x000000010001fe84
- (_Bool)_setDeveloperModeEnabled:(_Bool)arg1 error:(id *)arg2;	// IMP=0x000000010001fb4c
- (void)_authorizeDeveloperModeChangeWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010001fb38
- (id)_developerModeSemaphoreURL;	// IMP=0x000000010001fa84
- (_Bool)_connectionMayConnect:(id)arg1;	// IMP=0x000000010001fa74
- (_Bool)_connectionIsEntitled:(id)arg1 forMutation:(_Bool)arg2;	// IMP=0x000000010001f874
- (void)_waitForSiteApprovalWithServiceSpecifier:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x000000010001eea8
- (id)_serviceDetailsWithEntry:(id)arg1;	// IMP=0x000000010001ede0
- (id)_entriesWithServiceSpecifier:(id)arg1 URL:(id)arg2 limit:(unsigned long long)arg3 auditToken:(CDStruct_6ad76789)arg4;	// IMP=0x000000010001e6a8
- (void)_updateAllEntries:(id)arg1;	// IMP=0x000000010001dcb8
- (void)_addEntriesForAllBundlesWithEnumerator:(id)arg1 toWorkingSet:(id)arg2 enterpriseContext:(id)arg3 developerModeEnabled:(_Bool)arg4;	// IMP=0x000000010001da90

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

