//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface NRAnalytics : NSObject
{
    NSMutableDictionary *_eventDictionary;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010009b790
@property(retain, nonatomic) NSMutableDictionary *eventDictionary; // @synthesize eventDictionary=_eventDictionary;
- (void)reset;	// IMP=0x000000010009b778
- (void)submit;	// IMP=0x000000010009b774
- (void)reportEvent:(id)arg1;	// IMP=0x000000010009b57c
- (id)init;	// IMP=0x000000010009b448

@end

