//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NRBabelRoute.h"

@interface NRBabelRouteLocal : NRBabelRoute
{
}

- (void)applyUsingSystem;	// IMP=0x00000001000767ec
- (void)resetExpiryTimer;	// IMP=0x00000001000767e8
- (id)initWithPrefix:(id)arg1 instance:(id)arg2;	// IMP=0x0000000100076724
- (unsigned short)metric;	// IMP=0x000000010007671c
- (unsigned short)seqno;	// IMP=0x00000001000766d0

@end

