//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NRLink, NSUUID;

@interface NRLinkDirectorMessage : NSObject
{
    unsigned char _messageVersion;	// 8 = 0x8
    unsigned short _messageHeaderSize;	// 10 = 0xa
    unsigned short _payloadLength;	// 12 = 0xc
    unsigned int _messageLen;	// 16 = 0x10
    NRLink *_preferredLink;	// 24 = 0x18
    NSUUID *_nrUUID;	// 32 = 0x20
    char *_messageBufferPtr;	// 40 = 0x28
    unsigned long long _identifier;	// 48 = 0x30
}

+ (_Bool)testForNRUUID:(id)arg1;	// IMP=0x000000010000b8cc
+ (void)testCleanupForNRUUID:(id)arg1;	// IMP=0x000000010000b864
+ (_Bool)testMessage:(id)arg1;	// IMP=0x000000010000b0a0
+ (id)createTestEndpointIPv6;	// IMP=0x000000010000afd4
+ (id)createTestEndpointIPv4;	// IMP=0x000000010000af08
+ (id)createArrayFromSubDataArray:(id)arg1;	// IMP=0x000000010000adb8
+ (id)createSubDataArrayFromData:(id)arg1;	// IMP=0x000000010000ac84
+ (id)testData;	// IMP=0x000000010000aa7c
+ (id)createMessageWithData:(id)arg1 nrUUID:(id)arg2;	// IMP=0x000000010000a6d8
- (void).cxx_destruct;	// IMP=0x000000010000a558
@property(nonatomic) unsigned short payloadLength; // @synthesize payloadLength=_payloadLength;
@property(nonatomic) unsigned long long identifier; // @synthesize identifier=_identifier;
@property(nonatomic) unsigned int messageLen; // @synthesize messageLen=_messageLen;
@property(nonatomic) unsigned short messageHeaderSize; // @synthesize messageHeaderSize=_messageHeaderSize;
@property(nonatomic) unsigned char messageVersion; // @synthesize messageVersion=_messageVersion;
@property(nonatomic) char *messageBufferPtr; // @synthesize messageBufferPtr=_messageBufferPtr;
@property(retain, nonatomic) NSUUID *nrUUID; // @synthesize nrUUID=_nrUUID;
@property(retain, nonatomic) NRLink *preferredLink; // @synthesize preferredLink=_preferredLink;
- (_Bool)send;	// IMP=0x000000010000a304
- (id)copySendBuffer;	// IMP=0x000000010000a1d0
- (id)copyFirstDataForType:(unsigned char)arg1;	// IMP=0x000000010000a184
- (id)copyUpdateWiFiAddressEndpointsForInterfaceIndex:(unsigned int)arg1;	// IMP=0x0000000100009da8
- (id)copyFirstBoolForType:(unsigned char)arg1;	// IMP=0x0000000100009d14
- (_Bool)hasType:(unsigned char)arg1;	// IMP=0x0000000100009ce0
- (id)copyAllDataForType:(unsigned char)arg1;	// IMP=0x00000001000097ac
- (id)copyDeviceLinkState;	// IMP=0x0000000100009580
- (void)addDeviceLinkState:(id)arg1;	// IMP=0x000000010000921c
- (void)addUpdateWiFiAddressEndpoint:(id)arg1 portHBO:(unsigned short)arg2;	// IMP=0x0000000100008f74
- (void)addType:(unsigned char)arg1;	// IMP=0x0000000100008f64
- (void)addType:(unsigned char)arg1 boolValue:(_Bool)arg2;	// IMP=0x0000000100008eec
- (void)addType:(unsigned char)arg1 data:(id)arg2;	// IMP=0x0000000100008a84
- (id)description;	// IMP=0x00000001000089f0
- (void)dealloc;	// IMP=0x0000000100008738
- (id)initOutgoingDirectorMessageWithNRUUID:(id)arg1;	// IMP=0x00000001000086b4
- (id)initOutgoingDirectorMessageWithNRUUIDInner:(id)arg1 messageVersion:(unsigned char)arg2;	// IMP=0x0000000100008488
- (void)writeMessagePayloadLengthNBOToSendBuffer:(const char *)arg1 len:(unsigned short)arg2;	// IMP=0x000000010000821c
- (void)writeMessageIdentifierNBOToSendBuffer:(const char *)arg1 len:(unsigned int)arg2;	// IMP=0x0000000100007f7c
- (void)writeMessageOptionsToSendBuffer:(const char *)arg1 len:(unsigned char)arg2;	// IMP=0x0000000100007d54
- (void)writeMessageVersionToSendBuffer:(unsigned char)arg1;	// IMP=0x0000000100007b70
- (id)initDirectorMessageWithNRUUID:(id)arg1 messageLen:(unsigned int)arg2 messageVersion:(unsigned char)arg3;	// IMP=0x00000001000077d0

@end

