//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface RPAudioMixUtility : NSObject
{
}

+ (id)tempFileURL;	// IMP=0x0000000100018cf0
+ (void)mixAudioForMovie:(id)arg1 finalMovieURL:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100018550
+ (void)mixAudioForMovie:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100018424

@end

