//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSLock, NSMutableArray, Protocol;
@protocol OS_dispatch_queue;

@interface RPDelegateBase : NSObject
{
    NSMutableArray *_delegateArray;	// 8 = 0x8
    NSLock *_lock;	// 16 = 0x10
    _Bool _isValid;	// 24 = 0x18
    Protocol *_protocol;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_delegateQueue;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0000000100027580
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *delegateQueue; // @synthesize delegateQueue=_delegateQueue;
@property(nonatomic) Protocol *protocol; // @synthesize protocol=_protocol;
- (_Bool)containsDelegate:(id)arg1;	// IMP=0x000000010002742c
- (void)callDelegate:(CDUnknownBlockType)arg1 forProtocol:(id)arg2;	// IMP=0x0000000100027180
- (void)callDelegate:(CDUnknownBlockType)arg1;	// IMP=0x0000000100027170
- (_Bool)hasDelegate:(id)arg1;	// IMP=0x00000001000270f4
- (unsigned long long)delegateCount;	// IMP=0x00000001000270a0
- (void)removeAllDelegates;	// IMP=0x0000000100027050
- (void)removeDelegate:(id)arg1;	// IMP=0x0000000100026ed8
- (void)addDelegate:(id)arg1;	// IMP=0x0000000100026e58
- (_Bool)valid;	// IMP=0x0000000100026e14
- (void)invalidate;	// IMP=0x0000000100026dc0
- (void)dealloc;	// IMP=0x0000000100026cd0
- (id)init;	// IMP=0x0000000100026b30

@end

