//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RPSession.h"

#import "RPCaptureManagerProtocol-Protocol.h"

@class NSURL, RPMovieWriter;

@interface RPRecordSession : RPSession <RPCaptureManagerProtocol>
{
    RPMovieWriter *_movieWriter;	// 88 = 0x58
    NSURL *_currentRecordingURL;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x0000000100039ddc
- (void)handleResumeContextIDFailure;	// IMP=0x0000000100039b94
- (void)handleDeviceRestrictionWarning;	// IMP=0x000000010003994c
- (void)handleDeviceLockedWarning;	// IMP=0x000000010003986c
- (void)handleDisplayWarning;	// IMP=0x0000000100039624
- (void)handleClientApplicationDidEnterForeground;	// IMP=0x000000010003950c
- (void)handleClientApplicationDidEnterBackground;	// IMP=0x000000010003941c
- (void)handleResumeCaptureWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100039088
- (void)captureDidFailWithError:(id)arg1;	// IMP=0x0000000100038f44
- (void)didCaptureSampleWithType:(int)arg1 withSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 withTransformFlags:(unsigned long long)arg3;	// IMP=0x0000000100038dbc
- (void)presentAcknowledgmentWithMicrophoneEnabled:(_Bool)arg1 cameraEnabled:(_Bool)arg2 withHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001000388a0
- (id)dispatchCaptureQueue;	// IMP=0x0000000100038830
- (void)discardInAppRecordingWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001000386b4
- (void)pauseSession;	// IMP=0x000000010003852c
- (void)stopRecordingWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100038064
- (void)startRecordingWithMicrophoneEnabled:(_Bool)arg1 cameraEnabled:(_Bool)arg2 contextID:(id)arg3 windowSize:(struct CGSize)arg4 handler:(CDUnknownBlockType)arg5;	// IMP=0x0000000100037db8
- (id)outputPath;	// IMP=0x0000000100037d20

@end

