//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface GKAcceptedInviteManager : NSObject
{
    NSMutableArray *_acceptedMultiplayerInvites;	// 8 = 0x8
    NSMutableArray *_acceptedTurnBased;	// 16 = 0x10
    NSMutableArray *_acceptedTournamentInvites;	// 24 = 0x18
}

+ (id)syncQueue;	// IMP=0x00000001000b3670
@property(retain) NSMutableArray *acceptedTournamentInvites; // @synthesize acceptedTournamentInvites=_acceptedTournamentInvites;
@property(retain) NSMutableArray *acceptedTurnBased; // @synthesize acceptedTurnBased=_acceptedTurnBased;
@property(retain) NSMutableArray *acceptedMultiplayerInvites; // @synthesize acceptedMultiplayerInvites=_acceptedMultiplayerInvites;
- (id)description;	// IMP=0x00000001000b4aa0
- (id)tournamentInviteForGame:(id)arg1;	// IMP=0x00000001000b4944
- (id)turnBasedInviteForGameDescriptor:(id)arg1;	// IMP=0x00000001000b4808
- (id)turnBasedInviteForGame:(id)arg1;	// IMP=0x00000001000b46f8
- (id)multiplayerInviteForGameDescriptor:(id)arg1;	// IMP=0x00000001000b453c
- (id)multiplayerInviteForGame:(id)arg1;	// IMP=0x00000001000b442c
- (id)removeAndReturnTurnBasedInviteWithMatchID:(id)arg1;	// IMP=0x00000001000b42cc
- (id)removeAndReturnInviteWithSessionToken:(id)arg1;	// IMP=0x00000001000b416c
- (void)addTournamentInvite:(id)arg1;	// IMP=0x00000001000b4078
- (void)addTurnBasedEvent:(id)arg1;	// IMP=0x00000001000b3f84
- (void)addMultiplayerInvite:(id)arg1;	// IMP=0x00000001000b3e90
- (id)_fetchAndRemoveBulletinFromArray:(id)arg1 passingTest:(CDUnknownBlockType)arg2;	// IMP=0x00000001000b3bf8
- (void)_insertBulletin:(id)arg1 atFrontOfArray:(id)arg2;	// IMP=0x00000001000b3abc
- (void)_addBulletin:(id)arg1 toArray:(id)arg2;	// IMP=0x00000001000b3984
- (void)performSync:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b3794
- (void)dealloc;	// IMP=0x00000001000b3618
- (id)init;	// IMP=0x00000001000b35a8

@end

