//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class LSApplicationProxy, NSBundle, NSDate, NSDictionary, NSNumber, NSString;

@interface GKApplicationProxy : NSObject
{
    LSApplicationProxy *_lsProxy;	// 8 = 0x8
    NSDictionary *_metadata;	// 16 = 0x10
}

+ (id)metadataForBundleURL:(id)arg1;	// IMP=0x0000000100084924
@property(retain, nonatomic) NSDictionary *metadata; // @synthesize metadata=_metadata;
@property(retain, nonatomic) LSApplicationProxy *lsProxy; // @synthesize lsProxy=_lsProxy;
@property(readonly, retain, nonatomic) NSString *bundleShortVersion;
@property(readonly, retain, nonatomic) NSString *bundleVersion;
@property(readonly, nonatomic, getter=isInstalled) _Bool installed;
@property(readonly, nonatomic, getter=isGameCenterEnabled) _Bool gameCenterEnabled;
@property(readonly, nonatomic, getter=isRestricted) _Bool restricted;
@property(readonly, retain, nonatomic) NSDate *purchaseDate;
- (id)bundleURL;	// IMP=0x0000000100084b1c
@property(readonly, retain, nonatomic) NSNumber *externalVersion;
@property(readonly, retain, nonatomic) NSNumber *adamID;
@property(readonly, retain, nonatomic) NSString *bundleID;
@property(readonly, retain, nonatomic) NSBundle *bundle;
- (void)dealloc;	// IMP=0x00000001000849fc
- (id)initWithBundleID:(id)arg1;	// IMP=0x00000001000848e4
- (id)initWithProxy:(id)arg1;	// IMP=0x0000000100084884

@end

