//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface GKAuthenticationMachine : NSObject <NSCoding>
{
    long long _loginCancelledCount;	// 8 = 0x8
    NSString *_accountName;	// 16 = 0x10
    long long _serverEnvironment;	// 24 = 0x18
}

+ (void)migratePreSundanceAccountInformation;	// IMP=0x000000010007fadc
+ (void)migratePreBlacktailAccountInformation;	// IMP=0x000000010007f82c
+ (id)authMachineForEnvironment:(long long)arg1;	// IMP=0x000000010007f670
+ (_Bool)supportsSecureCoding;	// IMP=0x000000010007f668
@property(nonatomic) long long serverEnvironment; // @synthesize serverEnvironment=_serverEnvironment;
@property(retain, nonatomic) NSString *accountName; // @synthesize accountName=_accountName;
@property(nonatomic) long long loginCancelledCount; // @synthesize loginCancelledCount=_loginCancelledCount;
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000010007f784
- (void)dealloc;	// IMP=0x000000010007f73c
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010007f678

@end

