//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKFriendListCacheObject.h"

@interface GKFriendRequestListCacheObject : GKFriendListCacheObject
{
}

+ (Class)entryClass;	// IMP=0x000000010004df90
+ (id)entityName;	// IMP=0x000000010004df84
- (id)internalRepresentation;	// IMP=0x000000010004e364
- (void)updateWithServerRepresentation:(id)arg1 expirationDate:(id)arg2;	// IMP=0x000000010004df9c

@end

