//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKCacheReader.h"

@interface GKFriendRequestsCacheReader : GKCacheReader
{
}

+ (id)readerWithDatabaseConnection:(id)arg1;	// IMP=0x00000001000d9928
- (void)readResources:(id)arg1 inDatabase:(struct sqlite3 *)arg2 statementStore:(id)arg3 handler:(CDUnknownBlockType)arg4;	// IMP=0x00000001000d9a58
- (void)bindParametersForStatement:(struct sqlite3_stmt *)arg1 withPlayer:(id)arg2;	// IMP=0x00000001000d9a18
- (id)getExpirationDateStatement;	// IMP=0x00000001000d99c0
- (id)getRequestingPlayerGCIDsStatement;	// IMP=0x00000001000d995c

@end

