//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue, OS_xpc_object;

@interface PKDaemonClient : NSObject
{
    NSObject<OS_xpc_object> *_pkd;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_replyQueue;	// 16 = 0x10
    long long _protocolVersion;	// 24 = 0x18
}

+ (id)convertToXPC:(id)arg1 version:(unsigned long long)arg2;	// IMP=0x000000010001b3c4
- (void).cxx_destruct;	// IMP=0x000000010001b484
@property long long protocolVersion; // @synthesize protocolVersion=_protocolVersion;
@property(retain) NSObject<OS_dispatch_queue> *replyQueue; // @synthesize replyQueue=_replyQueue;
@property(retain) NSObject<OS_xpc_object> *pkd; // @synthesize pkd=_pkd;
- (id)convertFromXPC:(id)arg1;	// IMP=0x000000010001b3ec
- (void)set:(id)arg1 uuids:(id)arg2;	// IMP=0x000000010001b240
- (void)set:(id)arg1 plugins:(id)arg2;	// IMP=0x000000010001af64
- (void)sendSynchronously:(_Bool)arg1 request:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010001adb0
- (void)send:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001ad5c
- (id)request:(const char *)arg1 paths:(id)arg2;	// IMP=0x000000010001acd0
- (id)request:(const char *)arg1;	// IMP=0x000000010001ac5c
- (void)copyReceipt:(CDUnknownBlockType)arg1;	// IMP=0x000000010001abe0
- (void)releaseHold:(id)arg1 flags:(unsigned long long)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010001aab8
- (void)holdPlugins:(id)arg1 flags:(unsigned long long)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010001a9fc
- (void)bulkSetPluginAnnotations:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001a938
- (void)setPluginAnnotations:(id)arg1 annotations:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010001a844
- (void)matchPlugIns:(id)arg1 flags:(unsigned long long)arg2 uuid:(id)arg3 reply:(CDUnknownBlockType)arg4;	// IMP=0x000000010001a6e8
- (void)findPlugInByPathURL:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001a5fc
- (void)findPlugInByUUID:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001a508
- (void)accessPlugIns:(id)arg1 synchronously:(_Bool)arg2 flags:(unsigned long long)arg3 reply:(CDUnknownBlockType)arg4;	// IMP=0x000000010001a438
- (void)readyPlugIns:(id)arg1 synchronously:(_Bool)arg2 flags:(unsigned long long)arg3 environment:(id)arg4 reply:(CDUnknownBlockType)arg5;	// IMP=0x000000010001a31c
- (void)bulkPlugins:(unsigned long long)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001a28c
- (void)removePlugIns:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001a1f4
- (void)addPlugIns:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010001a15c
- (id)errorInReply:(id)arg1;	// IMP=0x0000000100019ff0
- (id)initWithServiceName:(const char *)arg1 user:(unsigned int)arg2;	// IMP=0x0000000100019e2c
- (id)initWithServiceName:(const char *)arg1;	// IMP=0x0000000100019e1c

@end

