//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ASURLSessionManager.h"

@class NSMutableDictionary, NSObject;
@protocol OS_dispatch_queue;

@interface ASAssetMetadataDownloader : ASURLSessionManager
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    NSMutableDictionary *_data;	// 16 = 0x10
    NSMutableDictionary *_completions;	// 24 = 0x18
    double _defaultNetworkTimeout;	// 32 = 0x20
}

@property(nonatomic) double defaultNetworkTimeout; // @synthesize defaultNetworkTimeout=_defaultNetworkTimeout;
- (void)URLSession:(id)arg1 _willRetryBackgroundDataTask:(id)arg2;	// IMP=0x000000010003caec
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;	// IMP=0x000000010003c7f4
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010003c3ec
- (void)URLSession:(id)arg1 _taskIsWaitingForConnection:(id)arg2;	// IMP=0x000000010003c3ac
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;	// IMP=0x000000010003c168
- (void)downloadMetadataFromURL:(id)arg1 withOptions:(id)arg2 ifNewerThan:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x000000010003be2c
- (id)_lastModifiedDateFromResponse:(id)arg1;	// IMP=0x000000010003bdac
- (id)_translateError:(id)arg1;	// IMP=0x000000010003bca8
- (void)dealloc;	// IMP=0x000000010003bc38
- (id)init;	// IMP=0x000000010003bb98
- (id)_sessionForOptions:(id)arg1;	// IMP=0x000000010003ba94
- (_Bool)_canUseBackgroundSession;	// IMP=0x000000010003ba48
- (id)sessionConfigurationWithIdentifier:(id)arg1 options:(id)arg2;	// IMP=0x000000010003b8cc

@end

