//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface CKKSSQLDatabaseObject : NSObject <NSCopying>
{
    NSDictionary *_originalSelfWhereClause;	// 8 = 0x8
}

+ (id)sqlColumns;	// IMP=0x000000010002f7f0
+ (id)sqlTable;	// IMP=0x000000010002f740
+ (id)fromDatabaseRow:(id)arg1;	// IMP=0x000000010002f684
+ (id)fetch:(unsigned long long)arg1 where:(id)arg2 orderBy:(id)arg3 error:(id *)arg4;	// IMP=0x000000010002f4dc
+ (id)fetch:(unsigned long long)arg1 where:(id)arg2 error:(id *)arg3;	// IMP=0x000000010002f4c8
+ (id)fetch:(unsigned long long)arg1 error:(id *)arg2;	// IMP=0x000000010002f4b0
+ (id)allWhere:(id)arg1 error:(id *)arg2;	// IMP=0x000000010002f32c
+ (id)all:(id *)arg1;	// IMP=0x000000010002f318
+ (id)tryFromDatabaseWhere:(id)arg1 error:(id *)arg2;	// IMP=0x000000010002f1a8
+ (id)fromDatabaseWhere:(id)arg1 error:(id *)arg2;	// IMP=0x000000010002f040
+ (_Bool)deleteAll:(id *)arg1;	// IMP=0x000000010002efcc
+ (_Bool)performCKKSReadonlyTransaction:(CDUnknownBlockType)arg1;	// IMP=0x000000010002ee84
+ (_Bool)performCKKSTransaction:(CDUnknownBlockType)arg1;	// IMP=0x000000010002ed3c
+ (_Bool)queryMaxValueForField:(id)arg1 inTable:(id)arg2 where:(id)arg3 columns:(id)arg4 processRow:(CDUnknownBlockType)arg5;	// IMP=0x000000010002eb84
+ (id)quotedString:(id)arg1;	// IMP=0x000000010002eaec
+ (_Bool)queryDatabaseTable:(id)arg1 where:(id)arg2 columns:(id)arg3 groupBy:(id)arg4 orderBy:(id)arg5 limit:(long long)arg6 processRow:(CDUnknownBlockType)arg7 error:(id *)arg8;	// IMP=0x000000010002e8b4
+ (_Bool)deleteFromTable:(id)arg1 where:(id)arg2 connection:(struct __OpaqueSecDbConnection *)arg3 error:(id *)arg4;	// IMP=0x000000010002e730
+ (void)bindWhereClause:(struct sqlite3_stmt *)arg1 whereDict:(id)arg2 cferror:(struct __CFError **)arg3;	// IMP=0x000000010002e624
+ (id)orderByClause:(id)arg1;	// IMP=0x000000010002e524
+ (id)groupByClause:(id)arg1;	// IMP=0x000000010002e438
+ (id)makeWhereClause:(id)arg1;	// IMP=0x000000010002e34c
+ (_Bool)saveToDatabaseTable:(id)arg1 row:(id)arg2 connection:(struct __OpaqueSecDbConnection *)arg3 error:(id *)arg4;	// IMP=0x000000010002e1d0
+ (_Bool)deleteAll:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000588a4
+ (id)all:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100058780
+ (id)allUUIDs:(id)arg1 error:(id *)arg2;	// IMP=0x000000010005854c
- (void).cxx_destruct;	// IMP=0x000000010002e1c4
@property(copy) NSDictionary *originalSelfWhereClause; // @synthesize originalSelfWhereClause=_originalSelfWhereClause;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x000000010002e15c
- (id)whereClauseToFindSelf;	// IMP=0x000000010002e0ac
- (id)sqlValues;	// IMP=0x000000010002dffc
- (id)memoizeOriginalSelfWhereClause;	// IMP=0x000000010002dfb8
- (_Bool)deleteFromDatabase:(id *)arg1;	// IMP=0x000000010002df18
- (_Bool)saveToDatabaseWithConnection:(struct __OpaqueSecDbConnection *)arg1 error:(id *)arg2;	// IMP=0x000000010002dd54
- (_Bool)saveToDatabase:(id *)arg1;	// IMP=0x000000010002dd40

@end

