//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "CKKSPeerProvider-Protocol.h"

@class CKKSListenerCollection, CuttlefishXPCWrapper, NSString;

__attribute__((visibility("hidden")))
@interface OctagonCKKSPeerAdapter : NSObject <CKKSPeerProvider>
{
    _Bool _essential;	// 8 = 0x8
    NSString *_providerID;	// 16 = 0x10
    NSString *_peerID;	// 24 = 0x18
    CuttlefishXPCWrapper *_cuttlefishXPCWrapper;	// 32 = 0x20
    NSString *_containerName;	// 40 = 0x28
    NSString *_contextID;	// 48 = 0x30
    CKKSListenerCollection *_peerChangeListeners;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x0000000100044870
@property(retain) CKKSListenerCollection *peerChangeListeners; // @synthesize peerChangeListeners=_peerChangeListeners;
@property(readonly) NSString *contextID; // @synthesize contextID=_contextID;
@property(readonly) NSString *containerName; // @synthesize containerName=_containerName;
@property(readonly) CuttlefishXPCWrapper *cuttlefishXPCWrapper; // @synthesize cuttlefishXPCWrapper=_cuttlefishXPCWrapper;
@property(retain) NSString *peerID; // @synthesize peerID=_peerID;
@property(readonly) NSString *providerID; // @synthesize providerID=_providerID;
@property _Bool essential; // @synthesize essential=_essential;
- (id)currentState;	// IMP=0x00000001000447ec
- (void)sendTrustedPeerSetChangedUpdate;	// IMP=0x0000000100044768
- (void)sendSelfPeerChangedUpdate;	// IMP=0x00000001000446e4
- (void)registerForPeerChangeUpdates:(id)arg1;	// IMP=0x0000000100044678
- (id)fetchTrustedPeers:(id *)arg1;	// IMP=0x0000000100044474
- (id)fetchSelfPeers:(id *)arg1;	// IMP=0x0000000100044128
- (id)fetchIdentity:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100043f64
@property(readonly, copy) NSString *description;
- (id)initWithPeerID:(id)arg1 containerName:(id)arg2 contextID:(id)arg3 cuttlefishXPC:(id)arg4;	// IMP=0x0000000100043d68

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

