//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, PHFetchResult;

@interface TVPFetchManager : NSObject
{
    PHFetchResult *_rootFetchResult;	// 8 = 0x8
    NSMutableDictionary *_objectsToFetchResultsMapping;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100046028
@property(retain, nonatomic) NSMutableDictionary *objectsToFetchResultsMapping; // @synthesize objectsToFetchResultsMapping=_objectsToFetchResultsMapping;
@property(retain, nonatomic) PHFetchResult *rootFetchResult; // @synthesize rootFetchResult=_rootFetchResult;
- (void)_setFetchResult:(id)arg1 forObject:(id)arg2;	// IMP=0x0000000100045fb0
- (id)fetchManagerByApplyingChange:(id)arg1;	// IMP=0x0000000100045d9c
- (id)fetchResultForObject:(id)arg1 missBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100045cd8
- (id)initWithFetchResult:(id)arg1;	// IMP=0x0000000100045c34

@end

