//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UINavigationController.h>

#import "UINavigationControllerDelegate-Protocol.h"

@class NSString;

@interface TVPNavigationController : UINavigationController <UINavigationControllerDelegate>
{
}

- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;	// IMP=0x000000010008da44
- (void)setDelegate:(id)arg1;	// IMP=0x000000010008d98c
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010008d8f0
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010008d860
- (void)pu_configureAsRootViewController;	// IMP=0x0000000100049810

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

