//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITabBarController.h>

@interface TVPPhotoLibraryTabViewController : UITabBarController
{
}

- (void)setSelectedViewController:(id)arg1;	// IMP=0x000000010005b998
- (void)ppt_navigateToTabMode:(long long)arg1 animated:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x000000010005b858
- (void)navigateToTabMode:(long long)arg1 animated:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x000000010005b7b4
- (id)_viewControllerForMode:(long long)arg1;	// IMP=0x000000010005b638

@end

