//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTApplication.h"

@interface MTApplication_ATV : MTApplication
{
}

+ (id)appController;	// IMP=0x00000001001563b8
- (id)delegate;	// IMP=0x00000001001563f4

@end

