//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTTableViewCell.h"

@class UILabel;

@interface MTInformativeTableViewCell : MTTableViewCell
{
    UILabel *_messageLabel;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0000000100155ddc
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
- (struct CGSize)fittingSize;	// IMP=0x0000000100155d78
- (void)layoutSubviews;	// IMP=0x0000000100155c8c
- (void)setupCell;	// IMP=0x0000000100155628

@end

