//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MTLibraryLegacyUtil : NSObject
{
}

+ (long long)legacyPlayCountForPlayState:(long long)arg1 playCount:(long long)arg2;	// IMP=0x00000001000d34e0
+ (_Bool)hasBeenPlayedForPlayState:(long long)arg1;	// IMP=0x00000001000d34d4
+ (long long)playStateFromHasBeenPlayed:(_Bool)arg1 andPlayCount:(long long)arg2;	// IMP=0x00000001000d34bc

@end

