//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTListResultsController.h"

@class MTPlayerManifest;

@interface MTManifestResultsController : MTListResultsController
{
    MTPlayerManifest *_manifest;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010016be0c
@property(retain, nonatomic) MTPlayerManifest *manifest; // @synthesize manifest=_manifest;
- (void)_manifestDidChange;	// IMP=0x000000010016bd94
- (void)reloadData;	// IMP=0x000000010016bbfc
- (unsigned long long)startingIndexForDisplay;	// IMP=0x000000010016bba8
- (void)dealloc;	// IMP=0x000000010016ba84
- (id)init;	// IMP=0x000000010016b988

@end

