//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSNumber, NSString;

@interface MTMLMediaItem : NSObject
{
    _Bool _isItunesU;	// 8 = 0x8
    _Bool _hasBeenPlayed;	// 9 = 0x9
    _Bool _isExplicit;	// 10 = 0xa
    _Bool _isFromITunesSync;	// 11 = 0xb
    _Bool _isMissingAsset;	// 12 = 0xc
    NSString *_artist;	// 16 = 0x10
    NSNumber *_persistentId;	// 24 = 0x18
    NSNumber *_storeTrackId;	// 32 = 0x20
    NSNumber *_podcastPersistentId;	// 40 = 0x28
    NSNumber *_storeCollectionId;	// 48 = 0x30
    NSNumber *_byteSize;	// 56 = 0x38
    NSString *_category;	// 64 = 0x40
    NSNumber *_duration;	// 72 = 0x48
    NSString *_title;	// 80 = 0x50
    NSString *_assetUrl;	// 88 = 0x58
    NSString *_uti;	// 96 = 0x60
    NSString *_guid;	// 104 = 0x68
    NSDate *_pubDate;	// 112 = 0x70
    NSNumber *_playhead;	// 120 = 0x78
    NSNumber *_playCount;	// 128 = 0x80
    NSString *_feedUrl;	// 136 = 0x88
    NSString *_podcastTitle;	// 144 = 0x90
    NSNumber *_downloadIdentifier;	// 152 = 0x98
    NSDate *_lastPlayedDate;	// 160 = 0xa0
}

+ (_Bool)isMediaItemSyncedFromiTunes:(id)arg1;	// IMP=0x00000001000a0950
+ (id)propertiesForMediaItem;	// IMP=0x00000001000a07a4
+ (_Bool)isMissingAssetForItem:(id)arg1;	// IMP=0x00000001000a062c
+ (_Bool)isMissingFilePathForItem:(id)arg1;	// IMP=0x00000001000a05cc
+ (id)itemWithMPMediaItem:(id)arg1 isRestoreDownloadCandidate:(_Bool)arg2;	// IMP=0x000000010009fddc
+ (id)itemWithMPMediaItem:(id)arg1;	// IMP=0x000000010009fdcc
- (void).cxx_destruct;	// IMP=0x00000001000a0b80
@property(retain, nonatomic) NSDate *lastPlayedDate; // @synthesize lastPlayedDate=_lastPlayedDate;
@property(nonatomic) _Bool isMissingAsset; // @synthesize isMissingAsset=_isMissingAsset;
@property(nonatomic) _Bool isFromITunesSync; // @synthesize isFromITunesSync=_isFromITunesSync;
@property(nonatomic) _Bool isExplicit; // @synthesize isExplicit=_isExplicit;
@property(retain, nonatomic) NSNumber *downloadIdentifier; // @synthesize downloadIdentifier=_downloadIdentifier;
@property(retain, nonatomic) NSString *podcastTitle; // @synthesize podcastTitle=_podcastTitle;
@property(retain, nonatomic) NSString *feedUrl; // @synthesize feedUrl=_feedUrl;
@property(retain, nonatomic) NSNumber *playCount; // @synthesize playCount=_playCount;
@property(retain, nonatomic) NSNumber *playhead; // @synthesize playhead=_playhead;
@property(nonatomic) _Bool hasBeenPlayed; // @synthesize hasBeenPlayed=_hasBeenPlayed;
@property(retain, nonatomic) NSDate *pubDate; // @synthesize pubDate=_pubDate;
@property(retain, nonatomic) NSString *guid; // @synthesize guid=_guid;
@property(retain, nonatomic) NSString *uti; // @synthesize uti=_uti;
@property(nonatomic) _Bool isItunesU; // @synthesize isItunesU=_isItunesU;
@property(retain, nonatomic) NSString *assetUrl; // @synthesize assetUrl=_assetUrl;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSNumber *duration; // @synthesize duration=_duration;
@property(retain, nonatomic) NSString *category; // @synthesize category=_category;
@property(retain, nonatomic) NSNumber *byteSize; // @synthesize byteSize=_byteSize;
@property(retain, nonatomic) NSNumber *storeCollectionId; // @synthesize storeCollectionId=_storeCollectionId;
@property(retain, nonatomic) NSNumber *podcastPersistentId; // @synthesize podcastPersistentId=_podcastPersistentId;
@property(retain, nonatomic) NSNumber *storeTrackId; // @synthesize storeTrackId=_storeTrackId;
@property(retain, nonatomic) NSNumber *persistentId; // @synthesize persistentId=_persistentId;
@property(retain, nonatomic) NSString *artist; // @synthesize artist=_artist;
- (id)description;	// IMP=0x00000001000a06d8

@end

