//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IMUIUtil/IMActionSheetAction.h>

@interface MTMoreActionSheetAction : IMActionSheetAction
{
}

+ (id)moreIcon;	// IMP=0x000000010009b508
+ (id)action;	// IMP=0x000000010009b0ac
- (id)init;	// IMP=0x000000010009b0c4

@end

