//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <PodcastsUI/IMPlayerManifest.h>

#import "IMMetricsDataSource-Protocol.h"

@class MTPlayerItem, NSString;

@interface MTPlayerManifest : IMPlayerManifest <IMMetricsDataSource>
{
    _Bool _networkUPPEnabled;	// 8 = 0x8
    unsigned long long _playReason;	// 16 = 0x10
    NSString *_manifestIdentifier;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000ecf38
@property(retain, nonatomic) NSString *manifestIdentifier; // @synthesize manifestIdentifier=_manifestIdentifier;
@property(nonatomic) _Bool networkUPPEnabled; // @synthesize networkUPPEnabled=_networkUPPEnabled;
@property(nonatomic) unsigned long long playReason; // @synthesize playReason=_playReason;
- (id)metricsAdditionalData;	// IMP=0x00000001000ecd50
- (id)metricsContentIdentifier;	// IMP=0x00000001000ecd3c
- (void)enumerateObjectsUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001000ecc8c
- (id)objectAtIndex:(unsigned long long)arg1;	// IMP=0x00000001000ecc50
- (_Bool)userActivityContainsPlayhead;	// IMP=0x00000001000ecb6c
- (id)activitySpotlightIdentifier;	// IMP=0x00000001000ecb64
- (id)activity;	// IMP=0x00000001000ecb08
- (id)init;	// IMP=0x00000001000eca5c

// Remaining properties
@property(nonatomic) unsigned long long currentIndex;
@property(readonly, nonatomic) MTPlayerItem *currentItem; // @dynamic currentItem;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

