//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSNumber, NSString;

@protocol MTPodcastIdentifier
@property(readonly, nonatomic) NSString *originalPodcastFeedURL;
@property(readonly, nonatomic) NSString *currentPodcastFeedURL;
@property(readonly, nonatomic) NSNumber *podcastAdamID;
@property(readonly, nonatomic) NSString *podcastUUID;
@end

