//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTPodcastCell.h"

@class UIView;

@interface MTPodcastPlaylistCell : MTPodcastCell
{
    UIView *_disabledView;	// 24 = 0x18
    _Bool _added;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00000001000d891c
@property(nonatomic, getter=isAdded) _Bool added; // @synthesize added=_added;
- (void)setEnabled:(_Bool)arg1;	// IMP=0x00000001000d8844
- (void)prepareForReuse;	// IMP=0x00000001000d87dc
- (void)layoutSubviews;	// IMP=0x00000001000d86c8
- (id)countView;	// IMP=0x00000001000d86c0
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x00000001000d8664

@end

