//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MTSettingHeaderAction, MTSettingsController, MTSettingsGroup, NSString;

@protocol MTSettingsControllerDelegate <NSObject>
- (void)settingsController:(MTSettingsController *)arg1 didChangeSettingValueAtIndex:(long long)arg2 inGroupWithIdentifier:(NSString *)arg3;
- (void)settingsController:(MTSettingsController *)arg1 removedSettingAtIndex:(long long)arg2 inGroupWithIdentifier:(NSString *)arg3;
- (void)settingsController:(MTSettingsController *)arg1 removedGroupAtIndex:(long long)arg2;
- (void)settingsController:(MTSettingsController *)arg1 didChangeHeaderAction:(MTSettingHeaderAction *)arg2 inGroupWithIdentifier:(NSString *)arg3;
- (void)settingsController:(MTSettingsController *)arg1 addedGroup:(MTSettingsGroup *)arg2 atIndex:(long long)arg3;
- (void)settingsController:(MTSettingsController *)arg1 reloadedGroupWithIdentifier:(NSString *)arg2;
@end

