//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MTSingleton : NSObject
{
}

+ (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001001484e0
+ (id)allocWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001001484c0
+ (id)sharedInstance;	// IMP=0x000000010014830c
- (id)copy;	// IMP=0x0000000100148500

@end

