//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTSetting.h"

@class NSString;

@interface MTTextSetting : MTSetting
{
    NSString *_placeholder;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010010cc08
@property(copy, nonatomic) NSString *placeholder; // @synthesize placeholder=_placeholder;

@end

