//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@interface MTTVTableViewCell : UITableViewCell
{
}

+ (id)reuseIdentifier;	// IMP=0x00000001000321a0
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x0000000100032340
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100032274
- (void)updateColors;	// IMP=0x0000000100032270
- (void)configureSubviews;	// IMP=0x000000010003226c
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x0000000100032214
- (id)init;	// IMP=0x00000001000321b4

@end

