//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTTVArtworkBaseCollectionViewCell.h"

@interface MTTVPodcastCollectionViewCell : MTTVArtworkBaseCollectionViewCell
{
    _Bool _dark;	// 8 = 0x8
}

@property(nonatomic) _Bool dark; // @synthesize dark=_dark;
- (void)loadImageForKey:(id)arg1;	// IMP=0x0000000100099c18

@end

