//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MTPodcast, UIImageView;

@interface MTTVPodcastEpisodePlaceholderViewController : UIViewController
{
    MTPodcast *_podcast;	// 8 = 0x8
    UIImageView *_imageView;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100031f68
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) MTPodcast *podcast; // @synthesize podcast=_podcast;
- (id)_fetchArtwork;	// IMP=0x0000000100031db0
- (_Bool)_isDarkBackground;	// IMP=0x0000000100031d60
- (void)_updateColors;	// IMP=0x0000000100031c9c
- (void)_update;	// IMP=0x0000000100031bf8
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x0000000100031ac4
- (void)viewDidLayoutSubviews;	// IMP=0x00000001000319f0
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001000319a0
- (void)viewDidLoad;	// IMP=0x0000000100031950
- (void)loadView;	// IMP=0x00000001000318b4
- (id)initWithPodcast:(id)arg1;	// IMP=0x0000000100031840

@end

