//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MTTVEpisodeListViewController, NSIndexPath, UIFocusAnimationCoordinator, UITableViewFocusUpdateContext;

@protocol MTTVEpisodeListViewControllerDelegate <NSObject>

@optional
- (void)detailListController:(MTTVEpisodeListViewController *)arg1 didTransitionToState:(long long)arg2;
- (void)detailListController:(MTTVEpisodeListViewController *)arg1 didUpdateFocusInContext:(UITableViewFocusUpdateContext *)arg2 withAnimationCoordinator:(UIFocusAnimationCoordinator *)arg3;
- (void)detailListController:(MTTVEpisodeListViewController *)arg1 didSelectRowAtIndexPath:(NSIndexPath *)arg2;
@end

