//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTPodcastSectionedDetailListController.h"

#import "MTShowSettingsViewControllerDelegate-Protocol.h"
#import "MTTVPodcastHeaderViewDelegate-Protocol.h"

@class MTAllPropertyChangesQueryObserver, MTPodcast, MTTVPodcastHeaderView, NSIndexPath, NSString, UILongPressGestureRecognizer, UITapGestureRecognizer;

@interface MTTVPodcastEpisodeListViewController : MTPodcastSectionedDetailListController <MTTVPodcastHeaderViewDelegate, MTShowSettingsViewControllerDelegate>
{
    NSIndexPath *_selectedIndexPath;	// 8 = 0x8
    MTPodcast *_podcast;	// 16 = 0x10
    MTTVPodcastHeaderView *_podcastHeaderView;	// 24 = 0x18
    UITapGestureRecognizer *_playButtonRecognizer;	// 32 = 0x20
    UITapGestureRecognizer *_playButtonRecognizerForHeader;	// 40 = 0x28
    UILongPressGestureRecognizer *_longPressRecognizer;	// 48 = 0x30
    MTAllPropertyChangesQueryObserver *_darkObserver;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x000000010011e330
@property(retain, nonatomic) MTAllPropertyChangesQueryObserver *darkObserver; // @synthesize darkObserver=_darkObserver;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressRecognizer; // @synthesize longPressRecognizer=_longPressRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *playButtonRecognizerForHeader; // @synthesize playButtonRecognizerForHeader=_playButtonRecognizerForHeader;
@property(retain, nonatomic) UITapGestureRecognizer *playButtonRecognizer; // @synthesize playButtonRecognizer=_playButtonRecognizer;
@property(retain, nonatomic) MTTVPodcastHeaderView *podcastHeaderView; // @synthesize podcastHeaderView=_podcastHeaderView;
@property(readonly, nonatomic) MTPodcast *podcast; // @synthesize podcast=_podcast;
- (id)selectedIndexPath;	// IMP=0x000000010011e26c
- (void)dealloc;	// IMP=0x000000010011e200
- (void)showSettings:(id)arg1 changedDeletedPlayedEpisodes:(long long)arg2;	// IMP=0x000000010011e1f4
- (void)showSettings:(id)arg1 changedEpisodeLimit:(long long)arg2;	// IMP=0x000000010011e1e8
- (void)showSettings:(id)arg1 changedNotifications:(_Bool)arg2;	// IMP=0x000000010011e1e4
- (void)showSettings:(id)arg1 changedSubscribed:(_Bool)arg2;	// IMP=0x000000010011e1e0
- (void)showSettings:(id)arg1 changedEpisodeOrderAscending:(_Bool)arg2;	// IMP=0x000000010011e1d4
- (void)showSettings:(id)arg1 changedShowType:(long long)arg2;	// IMP=0x000000010011e1c8
- (void)updateDarkPlacard;	// IMP=0x000000010011e0b0
- (_Bool)hasDarkPlacard;	// IMP=0x000000010011e01c
- (void)_refreshFeedIfNeeded;	// IMP=0x000000010011dcec
- (void)_resetGoDark;	// IMP=0x000000010011db54
- (void)_showSettings;	// IMP=0x000000010011da7c
- (_Bool)_isSectionForSettings:(long long)arg1;	// IMP=0x000000010011da00
- (_Bool)_isIndexPathForSettings:(id)arg1;	// IMP=0x000000010011d9c4
- (_Bool)_isSectionForDarkPlacard:(long long)arg1;	// IMP=0x000000010011d9a0
- (_Bool)_isIndexPathForDarkPlacard:(id)arg1;	// IMP=0x000000010011d958
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x000000010011d898
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x000000010011d860
- (void)setSelectedIndexPath:(id)arg1;	// IMP=0x000000010011d73c
- (_Bool)respondsToSelector:(SEL)arg1;	// IMP=0x000000010011d6e4
- (void)tableView:(id)arg1 didUpdateFocusInContext:(id)arg2 withAnimationCoordinator:(id)arg3;	// IMP=0x000000010011d47c
- (void)tableView:(id)arg1 willDisplayHeaderView:(id)arg2 forSection:(long long)arg3;	// IMP=0x000000010011d34c
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x000000010011d248
- (id)indexPathForPreferredFocusedViewInTableView:(id)arg1;	// IMP=0x000000010011cff8
- (_Bool)tableView:(id)arg1 canFocusRowAtIndexPath:(id)arg2;	// IMP=0x000000010011cfac
- (id)messageForEmptySection;	// IMP=0x000000010011cf1c
- (id)createEmptySectionCell;	// IMP=0x000000010011ce9c
- (_Bool)hasEmptySection;	// IMP=0x000000010011ce4c
- (void)reloadData;	// IMP=0x000000010011cd78
- (void)switchToTab:(unsigned long long)arg1;	// IMP=0x000000010011cd24
- (void)selectedItemAtIndexPath:(id)arg1;	// IMP=0x000000010011cc54
- (void)setCellStyle:(unsigned long long)arg1;	// IMP=0x000000010011cc50
- (id)rightButtonItems;	// IMP=0x000000010011cc48
- (void)configureCell:(id)arg1 withObject:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x000000010011ca5c
- (id)newCellInstanceWithReuseIdentifier:(id)arg1;	// IMP=0x000000010011c908
- (id)reuseIdentifierForRow:(id)arg1;	// IMP=0x000000010011c84c
- (void)podcastHeaderDidSwitchToTab:(unsigned long long)arg1;	// IMP=0x000000010011c7fc
- (void)longPressAction:(id)arg1;	// IMP=0x000000010011c664
- (void)playPauseButtonAction:(id)arg1;	// IMP=0x000000010011c514
- (id)deleteEpisodeAction;	// IMP=0x000000010011c150
- (struct CGRect)tableViewFrame;	// IMP=0x000000010011c068
- (struct CGRect)headerViewFrame;	// IMP=0x000000010011bf48
- (void)viewWillLayoutSubviews;	// IMP=0x000000010011bbbc
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010011bb6c
- (void)viewDidLoad;	// IMP=0x000000010011b610
- (id)initWithPodcast:(id)arg1;	// IMP=0x000000010011b538
- (id)initWithPodcastUUID:(id)arg1;	// IMP=0x000000010011b468

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

