//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTOptionsTableViewController.h"

@interface MTTVOptionsTableViewController : MTOptionsTableViewController
{
}

+ (id)footerFont;	// IMP=0x0000000100098ea0
- (void)_updateTextColorForCell:(id)arg1 selected:(_Bool)arg2;	// IMP=0x0000000100099378
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000992ec
- (void)viewWillLayoutSubviews;	// IMP=0x0000000100098f38
- (void)viewDidLoad;	// IMP=0x0000000100098ec0

@end

