//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MTItemListManifest.h"

@interface MTUpNextManifest : MTItemListManifest
{
}

- (void)_updateUpNext;	// IMP=0x0000000100108cb8
- (void)_mediaItemDidChange:(id)arg1;	// IMP=0x0000000100108ba4
- (void)_upNextItemsDidChange;	// IMP=0x0000000100108b30
- (_Bool)defaultToInitialIndexZero;	// IMP=0x0000000100108b28
- (void)setCurrentIndex:(unsigned long long)arg1;	// IMP=0x00000001001089c0
- (void)dealloc;	// IMP=0x0000000100108948
- (id)initWithPlayer:(id)arg1;	// IMP=0x00000001001087b0

@end

