//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TVSMSystemMenuStartupContext.h"

@interface TVSMMutableSystemMenuStartupContext : TVSMSystemMenuStartupContext
{
}

@property(nonatomic, getter=isHomeModuleAvailable) _Bool homeModuleAvailable; // @dynamic homeModuleAvailable;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100006728
- (id)init;	// IMP=0x00000001000066f0

@end

