//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionViewController.h>

#import "TVSMModuleDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class NSString, TVSMDefaultModuleDataSource, TVSMPeopleModuleDataSource, UICollectionViewDiffableDataSource;

@interface TVSMButtonGridCollectionViewController : UICollectionViewController <TVSMModuleDelegate, UICollectionViewDelegateFlowLayout, UINavigationControllerDelegate, UIViewControllerTransitioningDelegate>
{
    TVSMPeopleModuleDataSource *_peopleDataSource;	// 8 = 0x8
    TVSMDefaultModuleDataSource *_buttonDataSource;	// 16 = 0x10
    UICollectionViewDiffableDataSource *_diffableDataSource;	// 24 = 0x18
    struct CGRect _selectedCellFrame;	// 32 = 0x20
}

+ (id)_overlayAnimationSettingsForTransition:(unsigned long long)arg1;	// IMP=0x0000000100008138
- (void).cxx_destruct;	// IMP=0x0000000100008330
@property(readonly, nonatomic) UICollectionViewDiffableDataSource *diffableDataSource; // @synthesize diffableDataSource=_diffableDataSource;
@property(readonly, nonatomic) TVSMDefaultModuleDataSource *buttonDataSource; // @synthesize buttonDataSource=_buttonDataSource;
@property(readonly, nonatomic) TVSMPeopleModuleDataSource *peopleDataSource; // @synthesize peopleDataSource=_peopleDataSource;
@property(readonly, nonatomic) struct CGRect selectedCellFrame; // @synthesize selectedCellFrame=_selectedCellFrame;
- (void)_updateLayoutElementWithOverlayTransition:(unsigned long long)arg1;	// IMP=0x0000000100007fc0
- (id)tvsm_synchronizedDrawingFence;	// IMP=0x0000000100007f00
- (void)_updateSnapshot;	// IMP=0x0000000100007990
- (id)_moduleAtIndexPath:(id)arg1;	// IMP=0x00000001000078c4
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0000000100007738
- (void)moduleDidRequestSystemMenuDismissal:(id)arg1;	// IMP=0x00000001000076f0
- (void)moduleDidRequestOverlay:(id)arg1;	// IMP=0x0000000100007674
- (void)moduleDidRequestExpansion:(id)arg1;	// IMP=0x0000000100007410
- (void)moduleDidRequestDismissal:(id)arg1;	// IMP=0x0000000100007344
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;	// IMP=0x00000001000072c8
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;	// IMP=0x0000000100007278
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x00000001000071fc
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x00000001000071f4
- (id)indexPathForPreferredFocusedViewInCollectionView:(id)arg1;	// IMP=0x00000001000071d8
- (void)_configureCell:(id)arg1 withModuleAtIndexPath:(id)arg2;	// IMP=0x00000001000070dc
- (void)viewDidLoad;	// IMP=0x0000000100006d8c
- (void)dealloc;	// IMP=0x0000000100006cac
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100006c74
- (id)init;	// IMP=0x0000000100006a30

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

