//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@protocol TVHAccountSetupViewControllerDelegate;

@interface TVHAccountSetupViewController : UIViewController
{
    _Bool _authenticationInProgress;	// 8 = 0x8
    id <TVHAccountSetupViewControllerDelegate> _delegate;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00000001000bb368
@property(nonatomic) __weak id <TVHAccountSetupViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_notifyDidCancel;	// IMP=0x00000001000bb2d0
- (void)_notifyDidSucceedWithAccountName:(id)arg1;	// IMP=0x00000001000bb250
- (void)_presentError;	// IMP=0x00000001000baf90
- (void)_enableHomeSharingWithAccountName:(id)arg1 password:(id)arg2;	// IMP=0x00000001000bad44
- (void)_showShouldUseAccountDialog:(id)arg1;	// IMP=0x00000001000ba7b0
- (void)_showLoginWithAccount:(id)arg1;	// IMP=0x00000001000ba2ec
- (void)_showSetupUI;	// IMP=0x00000001000ba258
- (void)_handleApplicationWillEnterForegroundNotification:(id)arg1;	// IMP=0x00000001000ba214
@property(nonatomic, getter=isAuthenticationInProgress) _Bool authenticationInProgress; // @synthesize authenticationInProgress=_authenticationInProgress;
- (void)viewDidLoad;	// IMP=0x00000001000ba140
- (void)willMoveToParentViewController:(id)arg1;	// IMP=0x00000001000ba094
- (void)dealloc;	// IMP=0x00000001000ba01c
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00000001000b9f1c

@end

