//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TVHEpisodeAlbumViewController.h"

@interface TVHAudiobookViewController : TVHEpisodeAlbumViewController
{
}

- (id)initWithAudiobook:(id)arg1 mediaLibrary:(id)arg2 audiobooksFetchContext:(id)arg3;	// IMP=0x0000000100062734
- (id)initWithAlbum:(id)arg1 mediaLibrary:(id)arg2 albumsFetchContext:(id)arg3 albumItemsFetchRequest:(id)arg4;	// IMP=0x00000001000626ac

@end

