//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSString, UIImage, UIImageView, UILabel, UIVisualEffectView, _UIFloatingContentView;

@interface TVHButton : UIControl
{
    _UIFloatingContentView *_floatingContentView;	// 8 = 0x8
    UIVisualEffectView *_backgroundEffectView;	// 16 = 0x10
    UIImageView *_imageView;	// 24 = 0x18
    UILabel *_textLabel;	// 32 = 0x20
}

+ (id)setScreenSaverButton;	// IMP=0x000000010000de20
+ (id)playSlideshowButton;	// IMP=0x000000010000dd3c
+ (id)sortButton;	// IMP=0x000000010000dc9c
+ (id)shuffleButton;	// IMP=0x000000010000dbb8
+ (id)playMusicButton;	// IMP=0x000000010000dad4
- (void).cxx_destruct;	// IMP=0x0000000100036ee4
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIVisualEffectView *backgroundEffectView; // @synthesize backgroundEffectView=_backgroundEffectView;
@property(retain, nonatomic) _UIFloatingContentView *floatingContentView; // @synthesize floatingContentView=_floatingContentView;
- (id)_lazyTextLabel;	// IMP=0x0000000100036cf8
- (struct CGSize)_textLabelSizeWithMaxSize:(struct CGSize)arg1;	// IMP=0x0000000100036c7c
- (struct CGSize)_imageViewSizeWithMaxSize:(struct CGSize)arg1;	// IMP=0x0000000100036c00
- (struct CGRect)_contentFrame;	// IMP=0x0000000100036b54
- (void)_updateViewColors;	// IMP=0x0000000100036a84
- (void)_setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x00000001000369ec
- (_Bool)_canHandlePresses:(id)arg1;	// IMP=0x0000000100036958
- (unsigned long long)_currentControlState;	// IMP=0x0000000100036910
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010003684c
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x000000010003679c
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000001000366ec
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x00000001000365c8
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001000364fc
- (_Bool)canBecomeFocused;	// IMP=0x00000001000364f0
- (void)layoutSubviews;	// IMP=0x00000001000361dc
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x00000001000360bc
- (struct CGSize)intrinsicContentSize;	// IMP=0x00000001000360a4
- (void)setHighlighted:(_Bool)arg1;	// IMP=0x0000000100036094
@property(copy, nonatomic) NSString *text;
@property(retain, nonatomic) UIImage *image;
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100035c1c

@end

