//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSSet;
@protocol TVHDiffableDataSourceContentProvider;

@protocol TVHDiffableDataSourceContentProviderDelegate <NSObject>
- (void)diffableDataSourceContentProvider:(id <TVHDiffableDataSourceContentProvider>)arg1 contentDidChangeWithAnimateChanges:(_Bool)arg2 itemIdentifiersOfAmendedItems:(NSSet *)arg3;
@end

