//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TVHMediaLibraryTabBarItemViewController-Protocol.h"

@class NSSet, NSString, TVHITunesUMainViewController;

@interface TVHITunesUTabBarItemViewController : UIViewController <TVHMediaLibraryTabBarItemViewController>
{
    TVHITunesUMainViewController *_iTunesUMainViewController;	// 8 = 0x8
}

+ (id)new;	// IMP=0x00000001000b9090
- (void).cxx_destruct;	// IMP=0x00000001000b9500
@property(retain, nonatomic) TVHITunesUMainViewController *iTunesUMainViewController; // @synthesize iTunesUMainViewController=_iTunesUMainViewController;
- (void)didLoseSelection;	// IMP=0x00000001000b949c
- (void)didReceiveSelection;	// IMP=0x00000001000b945c
@property(readonly, nonatomic) unsigned long long selectedMediaCategoryType;
@property(readonly, copy, nonatomic) NSSet *mediaCategoryTypes;
@property(readonly, nonatomic) unsigned long long type;
- (void)viewDidLoad;	// IMP=0x00000001000b9304
- (id)initWithMediaLibrary:(id)arg1;	// IMP=0x00000001000b9264
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000b91dc
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x00000001000b9154
- (id)init;	// IMP=0x00000001000b90cc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

