//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, UIView;
@protocol TVHLockupLayout;

@interface TVHLockup : UIControl <UIGestureRecognizerDelegate>
{
    _Bool _ancestorFocused;	// 8 = 0x8
    id <TVHLockupLayout> _layout;	// 16 = 0x10
    UIView *_contentView;	// 24 = 0x18
    UIView *_footerView;	// 32 = 0x20
    double _focusedSizeIncrease;	// 40 = 0x28
}

+ (void)_prepareLockupCompopnentForReuse:(id)arg1;	// IMP=0x00000001000a2c24
+ (void)_updateLockupComponentsHighContrastAppearanceWithLockupComponent:(id)arg1 state:(unsigned long long)arg2;	// IMP=0x00000001000a2ba0
+ (void)_updateComponentAppearanceForLockupCompopnent:(id)arg1 state:(unsigned long long)arg2;	// IMP=0x00000001000a2a64
+ (_Bool)_inheritsAncestorHighlighting;	// IMP=0x00000001000a22c4
+ (id)_footerViewWithLockupLayout:(id)arg1;	// IMP=0x00000001000a208c
+ (id)_contentViewWithLockupLayout:(id)arg1;	// IMP=0x00000001000a2034
+ (id)new;	// IMP=0x00000001000a1b4c
- (void).cxx_destruct;	// IMP=0x00000001000a3078
@property(nonatomic, getter=isAncestorFocused) _Bool ancestorFocused; // @synthesize ancestorFocused=_ancestorFocused;
@property(nonatomic) double focusedSizeIncrease; // @synthesize focusedSizeIncrease=_focusedSizeIncrease;
@property(readonly, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(readonly, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(readonly, nonatomic) id <TVHLockupLayout> layout; // @synthesize layout=_layout;
- (_Bool)_canAncestorBecomeFocused;	// IMP=0x00000001000a2f78
- (struct CGSize)_contentViewSizeIncludingFocusIncrease;	// IMP=0x00000001000a2edc
- (void)_updateFooterGeometryIncludingVertically:(_Bool)arg1;	// IMP=0x00000001000a2d54
- (void)_updateFooterGeometry;	// IMP=0x00000001000a2d44
- (void)_updateFooterHorizontalGeometry;	// IMP=0x00000001000a2d34
- (_Bool)_canHandlePresses:(id)arg1;	// IMP=0x00000001000a2ca0
- (void)_updateLockupComponentsHighContrastAppearanceWithLockupState:(unsigned long long)arg1;	// IMP=0x00000001000a2ae8
- (void)_updateLockupComponentsAppearanceForLockupState:(unsigned long long)arg1;	// IMP=0x00000001000a29ac
- (unsigned long long)_currentState;	// IMP=0x00000001000a2964
- (unsigned long long)_currentStateByApplyingAncestorFocusState;	// IMP=0x00000001000a2918
- (unsigned long long)_currentStateForFocusUpdateContext:(id)arg1;	// IMP=0x00000001000a285c
- (void)_updateAppearanceWithState:(unsigned long long)arg1 animationCoordinator:(id)arg2;	// IMP=0x00000001000a2798
- (void)_updateAncestorFocusedAndAppearanceForFocusUpdateContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x00000001000a26f4
- (void)_handleHighConstrastFocusIndicatorsEnabledNotification:(id)arg1;	// IMP=0x00000001000a26bc
- (void)pressesEnded:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000001000a25fc
- (void)pressesCancelled:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000001000a2550
- (void)pressesBegan:(id)arg1 withEvent:(id)arg2;	// IMP=0x00000001000a24a4
- (void)setEnabled:(_Bool)arg1;	// IMP=0x00000001000a2414
- (void)setHighlighted:(_Bool)arg1;	// IMP=0x00000001000a2384
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x00000001000a22ec
- (_Bool)canBecomeFocused;	// IMP=0x00000001000a22cc
- (void)_ancestorWillUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;	// IMP=0x00000001000a222c
- (void)layoutSubviews;	// IMP=0x00000001000a215c
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x00000001000a20ac
- (struct CGSize)intrinsicContentSize;	// IMP=0x00000001000a2094
- (void)prepareForReuse;	// IMP=0x00000001000a1f90
- (void)dealloc;	// IMP=0x00000001000a1efc
- (id)initWithLayout:(id)arg1;	// IMP=0x00000001000a1d20
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000a1c98
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000a1c10
- (id)init;	// IMP=0x00000001000a1b88

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

