//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface TVHMediaEntitiesDataSourceSection : NSObject
{
    NSString *_identifier;	// 8 = 0x8
    NSArray *_itemCollections;	// 16 = 0x10
    NSString *_title;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000b2a74
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, copy, nonatomic) NSArray *itemCollections; // @synthesize itemCollections=_itemCollections;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)_itemCollectionForItemIndex:(unsigned long long)arg1 adjustedIndex:(unsigned long long *)arg2;	// IMP=0x00000001000b28a0
- (id)mediaEntityForIndex:(unsigned long long)arg1;	// IMP=0x00000001000b2800
- (long long)itemIndexForIndexTitle:(id)arg1;	// IMP=0x00000001000b2634
@property(readonly, copy, nonatomic) NSArray *indexTitles;
@property(readonly, copy, nonatomic) NSArray *mediaEntities;
@property(readonly, nonatomic) unsigned long long numberOfMediaEntities;
- (id)initWithIdentifier:(id)arg1 itemCollections:(id)arg2;	// IMP=0x00000001000b20fc

@end

