//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 00:23:19).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TVHMediaLibraryTabBarItemViewController-Protocol.h"

@class NSSet, NSString, TVHPhotosMainViewController;

@interface TVHPhotosTabBarItemViewController : UIViewController <TVHMediaLibraryTabBarItemViewController>
{
    TVHPhotosMainViewController *_photosMainViewController;	// 8 = 0x8
}

+ (id)new;	// IMP=0x0000000100035798
- (void).cxx_destruct;	// IMP=0x0000000100035c08
@property(retain, nonatomic) TVHPhotosMainViewController *photosMainViewController; // @synthesize photosMainViewController=_photosMainViewController;
- (void)didLoseSelection;	// IMP=0x0000000100035ba4
- (void)didReceiveSelection;	// IMP=0x0000000100035b64
@property(readonly, nonatomic) unsigned long long selectedMediaCategoryType;
@property(readonly, copy, nonatomic) NSSet *mediaCategoryTypes;
@property(readonly, nonatomic) unsigned long long type;
- (void)viewDidLoad;	// IMP=0x0000000100035a0c
- (id)initWithMediaLibrary:(id)arg1;	// IMP=0x000000010003596c
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000358e4
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x000000010003585c
- (id)init;	// IMP=0x00000001000357d4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

